{
  "hash": "8a95dba3610804cd854e05db4c764776",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"08a - Kick starter - Geographically Weighted Predictive Modelling\"\nauthor: \"Cathy C.\"\ndate: \"Oct 25, 2025\"\ndate-modified: \"last-modified\" #auto render date\nformat: html\nexecute: #how YML page work\n  echo: true #will show code\n  eval: true #will run code every time and show output\n  warning: false #dont show warning msg\n  freeze: true #controls rendering - no render if no changes\n---\n\n\n\n\n## Installing and Loading R packages\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(httr, tidyverse, sf, tmap, jsonlite, progress)\n```\n:::\n\n\n\n\n### Additional packages for predive modelling\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(spdep, GWmodel, SpatialML, rsample, Metrics, knitr,\n               kableExtra, spatialRF, randomForestExplainer)\n```\n:::\n\n\n\n\nprogress - to monitor and track the computation.\n\n## Geocoding HDB resale data\nWe use OneMap https://www.onemap.gov.sg/apidocs/\nhttps://www.onemap.gov.sg/apidocs/reverseGeocode\n\n\n### Basic version\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- read_csv(\n  \"data/rawdata/HDBresale.csv\") %>%\n  filter(flat_type == \"4 ROOM\") %>%\n  filter(month >= \"2025-09\" & month < \"2025-10\") # filter the sample data for the exercise.\n\nwrite_rds(HDBresale, \"data/rds/HDBresale.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- read_rds(\"data/rds/HDBresale.rds\")\nglimpse(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 964\nColumns: 11\n$ month               <chr> \"2025-09\", \"2025-09\", \"2025-09\", \"2025-09\", \"2025-…\n$ town                <chr> \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO …\n$ flat_type           <chr> \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", …\n$ block               <chr> \"337\", \"542\", \"456\", \"561\", \"542\", \"472\", \"546\", \"…\n$ street_name         <chr> \"ANG MO KIO AVE 1\", \"ANG MO KIO AVE 10\", \"ANG MO K…\n$ storey_range        <chr> \"01 TO 03\", \"04 TO 06\", \"10 TO 12\", \"10 TO 12\", \"0…\n$ floor_area_sqm      <dbl> 91, 93, 100, 92, 93, 92, 92, 98, 92, 98, 92, 108, …\n$ flat_model          <chr> \"New Generation\", \"New Generation\", \"New Generatio…\n$ lease_commence_date <dbl> 1982, 1981, 1980, 1980, 1981, 1979, 1981, 1978, 19…\n$ remaining_lease     <chr> \"55 years 05 months\", \"54 years 05 months\", \"53 ye…\n$ resale_price        <dbl> 530000, 550000, 560000, 550000, 480000, 512888, 51…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# street names is ST, but it's actually Sait.\nHDBresale$street_name <- gsub(\n  \"ST\\\\.\", \"SAINT\",\n  HDBresale$street_name\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# for multiple queries\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\"searchVal\" = address,\n                \"returnGeom\" = \"Y\",\n                \"getAddrDetails\" = \"N\", #No. can change to Y for comparison\n                \"pageNum\" = \"1\") \n  res <- GET(base_url, query = query) #get URL query\n  restext <- content(res, as = \"text\")\n  \n  output <- fromJSON(restext) %>%\n    as.data.frame %>%\n    select(results.LATITUDE, results.LONGITUDE)\n  \n  return(output)\n}\n```\n:::\n\n\n\n\nNeed below to run the functions\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$LATITUDE <- 0\nHDBresale$LONGITUDE <- 0\n\nfor(i in 1:nrow(HDBresale)){\n  temp_output <- geocode(HDBresale[i, 4], HDBresale[i, 5])\n  \n  HDBresale$LATITUDE[i] <- temp_output$results.LATITUDE\n  HDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n\n\n## Transform to sf data frame\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System: NA\n```\n\n\n:::\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale %>%\n  st_as_sf(\n    coords = c(\"LONGITUDE\", \"LATITUDE\"),\n    crs = 4326) %>% #if decimal degree\n  st_transform(crs = 3414)\n```\n:::\n\n\n\n\n\n## Load preschool data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool = st_read(\"data/rawdata/PreSchoolsLocation.kml\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PRESCHOOLS_LOCATION' from data source \n  `/Users/cathyc/Documents/cathyschu/ISSS626GEO/In-class_Ex/In-class_Ex08/data/rawdata/PreSchoolsLocation.kml' \n  using driver `KML'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\nFrom this we will have the geometry data for the preschools.\n\nNext we will derive a binary data to find out which schools are within 350 meters.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_350m <- st_is_within_distance(\n  HDBresale_sf, preschool, dist = 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(prischool_350m = map_int(within_350m, length)\n)\n```\n:::\n\n\n\n\n\n# Predictive modeling\n## Data import\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdata <- read_rds(\"data/rawdata/mdata.rds\")\n```\n:::\n\n\n\n\n## Data sampling\nCalibrating predictive models are computational intensive, especially random forest method is used.\nFor quick prototyping, a 10% sample will be selected at random from the data by using the code chunk below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nHDB_sample <- mdata %>%\n  sample_n(1500)\n```\n:::\n\n\n\n\n### Checking of overlapping point\n\n*** When using GWmodel to calibrate explanaroty or predictive models, it is very important to ensure that there are no overlapping point features *** \n\nBelow is to check if there are overlapping point feature - to do spatial jitter. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlapping_points <- HDB_sample %>%\n  mutate(overlap = lengths(st_equals(.,.)) > 1)\n```\n:::\n\n\n\n\nBelow we can have a look at overlapping_points, and see the new column overlap showing whether the location has overlapping points. We then calculate how many has overlapping points. In this sample data, we observed 453 overlapping points. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(overlapping_points)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 18 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 27363.82 ymin: 31714.45 xmax: 41466.54 ymax: 48032.56\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 × 19\n  resale_price floor_area_sqm storey_order remaining_lease_mths PROX_CBD\n         <dbl>          <dbl>        <int>                <dbl>    <dbl>\n1       405000            109            1                  787    11.7 \n2       500888             87            2                  662     6.56\n3       385000            103            2                  821    14.3 \n4       485000             93            2                 1147    13.9 \n5       418000             93            5                 1134    18.2 \n6       288000             84            1                  770    16.3 \n# ℹ 14 more variables: PROX_ELDERLYCARE <dbl>, PROX_HAWKER <dbl>,\n#   PROX_MRT <dbl>, PROX_PARK <dbl>, PROX_GOOD_PRISCH <dbl>, PROX_MALL <dbl>,\n#   PROX_CHAS <dbl>, PROX_SUPERMARKET <dbl>, WITHIN_350M_KINDERGARTEN <int>,\n#   WITHIN_350M_CHILDCARE <int>, WITHIN_350M_BUS <int>,\n#   WITHIN_1KM_PRISCH <int>, geometry <POINT [m]>, overlap <lgl>\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(overlapping_points$overlap == \"TRUE\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 453\n```\n\n\n:::\n:::\n\n\n\n\n## Spatial jitter\n\nst_jitter is used to move the point feature by 5m to avoid overlapping point features.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample <- HDB_sample %>%\n  st_jitter(amount = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nresale_split <- initial_split(HDB_sample,\n                              prop = 6.67/10,)\ntrain_data <- training(resale_split)\ntest_data <- testing(resale_split)\n```\n:::\n\n\n\n\n\n### Constructing the adaptive bandwidth gwr model\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths +\n    PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +\n    WITHIN_1KM_PRISCH,\n  data=train_data,\n  approach=\"CV\",\n  kernel=\"gaussian\",\n  adaptive=TRUE,\n  longlat=FALSE)\n\nwrite_rds(bw_adaptive, \"data/model/bw_adaptive.rds\")\n```\n:::\n\n\n\n\n### Constructing the adaptive bandwidth gwr model\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + \n    PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET +\n    WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH,\n  data=train_data,\n  bw=bw_adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE,\n  longlat = FALSE)\n\nwrite_rds(gwr_adaptive, \n          \"data/model/gwr_adaptive.rds\")\n```\n:::\n\n\n\n\n### Output\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-10-25 15:28:10.864562 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + storey_order + \n    remaining_lease_mths + PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER + \n    PROX_MRT + PROX_PARK + PROX_MALL + PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n    data = train_data, bw = bw_adaptive, kernel = \"gaussian\", \n    adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm storey_order remaining_lease_mths PROX_CBD PROX_ELDERLYCARE PROX_HAWKER PROX_MRT PROX_PARK PROX_MALL PROX_SUPERMARKET WITHIN_350M_KINDERGARTEN WITHIN_350M_CHILDCARE WITHIN_350M_BUS WITHIN_1KM_PRISCH\n   Number of data points: 1000\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-167624  -37265    -415   34811  224601 \n\n   Coefficients:\n                            Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)              115703.7    34303.4   3.373 0.000773 ***\n   floor_area_sqm             2778.6      292.3   9.507  < 2e-16 ***\n   storey_order              12698.2     1071.0  11.857  < 2e-16 ***\n   remaining_lease_mths        350.2       14.6  23.997  < 2e-16 ***\n   PROX_CBD                 -16225.6      630.1 -25.751  < 2e-16 ***\n   PROX_ELDERLYCARE         -11330.9     3220.8  -3.518 0.000455 ***\n   PROX_HAWKER              -19964.1     4021.1  -4.965 8.10e-07 ***\n   PROX_MRT                 -39652.5     5412.3  -7.326 4.92e-13 ***\n   PROX_PARK                -15878.3     4609.2  -3.445 0.000595 ***\n   PROX_MALL                -15910.9     6438.1  -2.471 0.013628 *  \n   PROX_SUPERMARKET         -18928.5    13305.0  -1.423 0.155150    \n   WITHIN_350M_KINDERGARTEN   9309.7     2024.3   4.599 4.80e-06 ***\n   WITHIN_350M_CHILDCARE     -1619.5     1181.0  -1.371 0.170572    \n   WITHIN_350M_BUS            -447.7      738.7  -0.606 0.544624    \n   WITHIN_1KM_PRISCH        -10698.0     1543.5  -6.931 7.55e-12 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 61270 on 985 degrees of freedom\n   Multiple R-squared: 0.7424\n   Adjusted R-squared: 0.7387 \n   F-statistic: 202.7 on 14 and 985 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 3.698259e+12\n   Sigma(hat): 60874.22\n   AIC:  24901.01\n   AICc:  24901.56\n   BIC:  24090.05\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 19 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                   Min.     1st Qu.      Median     3rd Qu.\n   Intercept                -1791428.88  -214446.81    21746.20   257578.83\n   floor_area_sqm              -3179.59     1231.26     2028.42     3305.14\n   storey_order                 3239.39     8099.55    10335.65    13828.45\n   remaining_lease_mths         -532.05      343.58      421.29      502.66\n   PROX_CBD                  -108605.52   -23395.68   -10648.30     -783.78\n   PROX_ELDERLYCARE          -261721.26   -25806.00    -5956.08    18381.34\n   PROX_HAWKER               -217081.26   -36085.21    -9972.22    21334.82\n   PROX_MRT                  -302039.97   -92333.72   -57017.51   -20446.74\n   PROX_PARK                 -258097.15   -33745.52   -16670.47     8320.49\n   PROX_MALL                 -274797.44   -35638.26     6943.53    48945.77\n   PROX_SUPERMARKET          -176198.56   -42935.81    -7711.04    30245.81\n   WITHIN_350M_KINDERGARTEN   -43551.70    -9105.71    -2535.12     5566.02\n   WITHIN_350M_CHILDCARE      -15142.40    -2227.73     1241.19     3473.07\n   WITHIN_350M_BUS            -10844.53    -1809.75      506.21     2313.07\n   WITHIN_1KM_PRISCH          -50621.92    -4109.15      357.23     4933.83\n                                  Max.\n   Intercept                1520325.69\n   floor_area_sqm              7811.16\n   storey_order               26827.20\n   remaining_lease_mths         775.98\n   PROX_CBD                  126370.94\n   PROX_ELDERLYCARE          178548.71\n   PROX_HAWKER               145934.03\n   PROX_MRT                  128454.43\n   PROX_PARK                  88656.74\n   PROX_MALL                 339627.85\n   PROX_SUPERMARKET          185488.00\n   WITHIN_350M_KINDERGARTEN   40733.28\n   WITHIN_350M_CHILDCARE      15751.82\n   WITHIN_350M_BUS            11737.06\n   WITHIN_1KM_PRISCH          32872.55\n   ************************Diagnostic information*************************\n   Number of data points: 1000 \n   Effective number of parameters (2trace(S) - trace(S'S)): 419.1226 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 580.8774 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 24103.97 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 23393.88 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 24424.61 \n   Residual sum of squares: 599896185272 \n   R-square value:  0.9582109 \n   Adjusted R-square value:  0.9280067 \n\n   ***********************************************************************\n   Program stops at: 2025-10-25 15:28:11.517889 \n```\n\n\n:::\n:::\n\n\n\n\n- Based on the result of the modelling above, p-value is much smaller than 0.05. \nWe see the adjusted R^2 = 0.7387, meaning that this model can explain 73% of the data using the variables. \n\n- The AICc = 24901.56 for Global Regression model is much larger than Geographically Weighted Regression's AICc = 24103.97. The difference of approximately 797.6 points is quite significant. This suggests the **GWR model provides meaningfully better predictions and fit**. \n\n\nExplanatory variables:\n\nPlot out the significant variables to show distribution and explain which ones have higher/lower influence over the model. \n\n## Collinearity\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n## Plot VIF\n```{.r}\nplot(vif) +\n  theme(axis.test.x - element_text(\n    angle = 45, hjust = 1\n  ))\n```\n\n\n## Predive Modeling using MLR\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}