{
  "hash": "31a6ffa5cc37c7008d47de81e930b732",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"03 - Spatio-Temporal Point Patterns Analysis\"\nauthor: \"Cathy C.\"\ndate: \"Sep 9, 2025\"\ndate-modified: \"last-modified\" #auto render date\nformat: html\nexecute: #how YML page work\n  echo: true #will show code\n  eval: true #will run code every time and show output\n  warning: false #dont show warning msg\n  freeze: true #controls rendering - no render if no changes\n---\n\n\n## Introduction\n\nIn this study, we are interested in understanding the spatial and spatio-temporal patterns of new businesses and firms established in Singapore. Based on the Singapore Standard Industrial Classification 2020, there are over 1,500 business types. Among these, we will focus on **Laundry services** (including Laundry and dry cleaning services and self-operated laundries), **Beauty services** (including Hairdressing salons/shops, beauty salons and spas, as well as manicure and pedicure services, and **Dental services**.\n\nThe 3 chosen businesses are essential for working adults / professionals to take care of self for outlook and health. We would like to observe how these activities evolve and potentially to enhance quality of life and well-being.\n\nWe will start from processing the data, perform Kernel Density Estimation, Clarke-Evans test, and then conduct analysis with visualisation and test results. First-order and second-order spatial and spatio-temporal analyses are conducted to understand the overall new businesses and their temporal patterns during the period of time Jan 2024 to June 2025.\n\nDue to data set sizes, we will analyse spatial patterns by quarter for Laundry Services and Dental Services, and by month for Beauty Services. Different spatial point pattern testing menthods are used to analyse the 3 business types: G-function for Dental Services, L-function for Beauty Services, and F-function for Laundry Services.\n\n## 1 Loading the R package\n\nWe will use **tidyverse, sf, tmap, tmap,** and **httr** packages to process data sets, along with other packages for computing KDE and plotting visualisations.\n\n| R Package | Purpose |\n|--------------------|----------------------------------------------------|\n| **tidyverse** | the **tidyverse** package is designed to make it easy to install and load core packages from the tidyverse in a single command. There are ggplot2, dplyr, tidyr, readr, purrr, and tibble, etc to manipulate, tidy, import, visualise data. |\n| **sf** | provides support for working with simple features, a standardized way to represent geographic vector data. It serves as a comprehensive tool for handling spatial data within the R environment. |\n| **tmap** | serves the purpose of creating thematic maps, offering a flexible and intuitive way to visualize spatial data. It is designed to produce both static and interactive maps using a consistent, layer-based syntax similar to `ggplot2`. |\n| **httr** | serves as a tool for interacting with web APIs and performing HTTP requests within the R environment. |\n| **knitr** | seamlessly integrate R code, its output (including text, tables, and graphics), and narrative text within a single document. |\n| **rvest** | simplify the process of scraping and manipulating web data. It allows for the extraction of information from websites and transforms it into a format suitable for analysis in R. |\n| **spatstat** | provides functions for spatial statistics with a strong focus on analysing spatial point patterns. |\n| **terra** | provides methods for manipulating geographic (spatial) data in both raster and vector formats. |\n| **raster** | provides functions which reads, writes, manipulates, analyses and model of gridded spatial data (i.e. raster). In this hands-on exercise, it will be used to convert image output generate by spatstat into raster format. |\n| **sparr** | provides a suite of functions for analyzing spatial and spatiotemporal point patterns, particularly focusing on the estimation and inference of relative risk surfaces. |\n\n: R Packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, sf, tmap, httr, knitr, rvest, spatstat, terra, raster, sparr)\n```\n:::\n\n\n\n## 2 The Data\n\nThere are mainly two raw public datasets used in this study.\n\n-   **ACRA (Accounting and Corporate Regulatory Authority) Information on Corporate Entities datasets**: contains the business entities information, including their names, registration, status, and location.\n-   **The Master Plan 2019 Boundary**: consists of the geographical boundary of Singapore at the planning subzone level. The data is based on URA Master Plan 2019.\n-   **Singapore Residents by Planning Area / Subzone, Age Group, Sex and Type of Dwelling, June 2024**: *respopagesextod2024.csv* is an aspatial data fie. It can be downloaded at Department of Statistics, Singapore.\n\n### 2.1 Importing ACRA data\n\nWe downloaded the ACRA (Accounting and Corporate Regulatory Authority) Information on Corporate Entities datasets from data.gov.sg, and will import the ACRA data and transform them as tibble frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfolder_path <- \"data/aspatial/acra\"\nfile_list <- list.files(path = folder_path,\n                        pattern = \"^ACRA*.*\\\\.csv$\",\n                        full.names = TRUE)\nacra_data <- file_list %>%\n  map_dfr(read_csv) #import and append all of them together!!\n```\n:::\n\n\n\nThen, we will write the data into .rds to store it in the data folder. This is so no need to process data every time.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(acra_data, \"data/rds/acra_data.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacra_data <- read_rds(\"data/rds/acra_data.rds\")\n```\n:::\n\n\n\n### 2.2 Tidying ACRA data\n\nWith this step, we will extract the business codes 9601, 9602, and 86204, then rename the columns and transform the data type necessarily.\n\nThe business types chosen are:\n\n| Business Code | Types / subtypes |\n|-----------------------|-------------------------------------------------|\n| **9601** | **Washing and (Dry-) Cleaning of Textile and Fur Products** |\n| 96011 | Laundry and dry cleaning services except self-operated laundries |\n| 96012 | Self-operated laundries |\n| **9602** | **Hairdressing, Beauty and Other Personal Care Services** |\n| 96021 | Hairdressing salons/shops (including barber shops) |\n| 96022 | Beauty salons and spas (including slimming, skin care and hair care centres) |\n| 96023 | Manicure and pedicure services |\n| **86024** | **Dental services** |\n\n: Business Code & Types\n\nWe use below code to retrieve the data between Jan 1, 2024 to June 30, 2025 for the 3 different major business types.\n\n::: panel-tabset\n## 9601\n\n**Washing and (Dry-) Cleaning of Textile and Fur Products** Business Code 9601 encompasses Laundry cleaning and self-operated laundries (96011 & 96012)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601 <- acra_data %>%\n  dplyr::select(1:24) %>%\n  filter(primary_ssic_code == 96011 | primary_ssic_code == 96012) %>%\n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         YEAR = year(date),\n         MONTH_NUM = month(date),\n         MONTH_ABBR = month(date, label = TRUE, abbr = TRUE)) %>% #this gives Jan, Feb, Mar...\n  mutate(postal_code = str_pad(postal_code,\n                               width = 6, side = \"left\", pad = \"0\")) %>% #if missing digits, will replace with zero.\nfilter(YEAR == 2024 | YEAR == 2025 & MONTH_NUM <= 6)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601 <- write_rds(biz_9601, \"data/rds/biz_9601.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601 <- read_rds(\"data/rds/biz_9601.rds\")\nglimpse(biz_9601)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 150\nColumns: 27\n$ uen                               <chr> \"202401518M\", \"202409043N\", \"2025075…\n$ issuance_agency_id                <chr> \"ACRA\", \"ACRA\", \"ACRA\", \"ACRA\", \"ACR…\n$ entity_name                       <chr> \"ALL DAY EVERYDAY PTE. LTD.\", \"ABEND…\n$ entity_type_description           <chr> \"Local Company\", \"Local Company\", \"L…\n$ business_constitution_description <chr> \"na\", \"na\", \"na\", \"na\", \"Sole-Propri…\n$ company_type_description          <chr> \"Exempt Private Company Limited by S…\n$ paf_constitution_description      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ entity_status_description         <chr> \"Live Company\", \"Live Company\", \"Liv…\n$ date                              <date> 2024-01-10, 2024-03-07, 2025-02-20,…\n$ uen_issue_date                    <date> 2024-01-10, 2024-03-07, 2025-02-20,…\n$ address_type                      <chr> \"LOCAL\", \"LOCAL\", \"LOCAL\", \"LOCAL\", …\n$ block                             <chr> \"105\", \"138\", \"7030\", \"160\", \"842G\",…\n$ street_name                       <chr> \"BISHAN STREET 12\", \"JOO SENG ROAD\",…\n$ level_no                          <chr> \"05\", \"02\", \"02\", \"14\", \"14\", \"na\", …\n$ unit_no                           <chr> \"242\", \"02\", \"11\", \"04\", \"86\", \"na\",…\n$ building_name                     <chr> \"BISHAN VIEW\", \"na\", \"NORTHSTAR @ AM…\n$ postal_code                       <chr> \"570105\", \"368361\", \"569880\", \"06891…\n$ other_address_line1               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ other_address_line2               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ account_due_date                  <chr> \"2026-07-31\", \"2026-07-31\", \"2026-08…\n$ annual_return_date                <chr> \"2025-06-29\", \"2025-07-01\", \"na\", \"n…\n$ primary_ssic_code                 <dbl> 96012, 96011, 96011, 96012, 96012, 9…\n$ primary_ssic_description          <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ primary_user_described_activity   <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ YEAR                              <dbl> 2024, 2024, 2025, 2025, 2024, 2025, …\n$ MONTH_NUM                         <dbl> 1, 3, 2, 6, 7, 4, 11, 1, 2, 5, 4, 4,…\n$ MONTH_ABBR                        <ord> Jan, Mar, Feb, Jun, Jul, Apr, Nov, J…\n```\n\n\n:::\n:::\n\n\n\n**There are 150 observations we have retrieved for this analysis.**\n\n## 9602\n\n**Hairdressing, Beauty and Other Personal Care Services** Business Code 9602 includes hair dressing, beauty salons and manicure & pedicure services.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602 <- acra_data %>%\n  dplyr::select(1:24) %>%\n  filter(primary_ssic_code == 96021 | primary_ssic_code == 96022 | primary_ssic_code == 96023) %>%\n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         YEAR = year(date),\n         MONTH_NUM = month(date),\n         MONTH_ABBR = month(date, label = TRUE, abbr = TRUE)) %>% #this gives Jan, Feb, Mar...\n  mutate(postal_code = str_pad(postal_code,\n                               width = 6, side = \"left\", pad = \"0\")) %>% #if missing digits, will replace with zero.\nfilter(YEAR == 2024 | YEAR == 2025 & MONTH_NUM <= 6)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602 <- write_rds(biz_9602, \"data/rds/biz_9602.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602 <- read_rds(\"data/rds/biz_9602.rds\")\nglimpse(biz_9602)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,762\nColumns: 27\n$ uen                               <chr> \"202400273N\", \"202400385D\", \"2024010…\n$ issuance_agency_id                <chr> \"ACRA\", \"ACRA\", \"ACRA\", \"ACRA\", \"ACR…\n$ entity_name                       <chr> \"A-VINZ (KV) PTE. LTD.\", \"ACTINIC VE…\n$ entity_type_description           <chr> \"Local Company\", \"Local Company\", \"L…\n$ business_constitution_description <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ company_type_description          <chr> \"Exempt Private Company Limited by S…\n$ paf_constitution_description      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ entity_status_description         <chr> \"Live Company\", \"Struck Off\", \"Live …\n$ date                              <date> 2024-01-02, 2024-01-02, 2024-01-06,…\n$ uen_issue_date                    <date> 2024-01-02, 2024-01-02, 2024-01-06,…\n$ address_type                      <chr> \"LOCAL\", \"LOCAL\", \"LOCAL\", \"LOCAL\", …\n$ block                             <chr> \"7030\", \"9\", \"67\", \"250\", \"1\", \"371\"…\n$ street_name                       <chr> \"ANG MO KIO AVENUE 5\", \"RAFFLES PLAC…\n$ level_no                          <chr> \"07\", \"19\", \"01\", \"19\", \"01\", \"B1\", …\n$ unit_no                           <chr> \"36\", \"21\", \"459\", \"03\", \"20\", \"60\",…\n$ building_name                     <chr> \"NORTHSTAR @ AMK\", \"REPUBLIC PLAZA\",…\n$ postal_code                       <chr> \"569880\", \"048619\", \"330067\", \"17910…\n$ other_address_line1               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ other_address_line2               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ account_due_date                  <chr> \"2026-07-31\", \"2025-07-31\", \"2026-07…\n$ annual_return_date                <chr> \"2025-07-30\", \"na\", \"2025-07-10\", \"2…\n$ primary_ssic_code                 <dbl> 96021, 96021, 96022, 96021, 96021, 9…\n$ primary_ssic_description          <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"BEAUT…\n$ primary_user_described_activity   <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ YEAR                              <dbl> 2024, 2024, 2024, 2024, 2024, 2024, …\n$ MONTH_NUM                         <dbl> 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, …\n$ MONTH_ABBR                        <ord> Jan, Jan, Jan, Jan, Jan, Jan, Feb, F…\n```\n\n\n:::\n:::\n\n\n\n**There are 1762 observations we have retrieved for this analysis.**\n\n## 86204\n\n**Dental services**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204 <- acra_data %>%\n  dplyr::select(1:24) %>%\n  filter(primary_ssic_code == 86204) %>%\n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         YEAR = year(date),\n         MONTH_NUM = month(date),\n         MONTH_ABBR = month(date, label = TRUE, abbr = TRUE)) %>% #this gives Jan, Feb, Mar...\n  mutate(postal_code = str_pad(postal_code,\n                               width = 6, side = \"left\", pad = \"0\")) %>% #if missing digits, will replace with zero.\nfilter(YEAR == 2024 | YEAR == 2025 & MONTH_NUM <= 6)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204 <- write_rds(biz_86204, \"data/rds/biz_86204.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204 <- read_rds(\"data/rds/biz_86204.rds\")\nglimpse(biz_86204)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 81\nColumns: 27\n$ uen                               <chr> \"202401990E\", \"202402057R\", \"2024020…\n$ issuance_agency_id                <chr> \"ACRA\", \"ACRA\", \"ACRA\", \"ACRA\", \"ACR…\n$ entity_name                       <chr> \"AZURE DENTAL PTE. LTD.\", \"ASTER DEN…\n$ entity_type_description           <chr> \"Local Company\", \"Local Company\", \"L…\n$ business_constitution_description <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ company_type_description          <chr> \"Exempt Private Company Limited by S…\n$ paf_constitution_description      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ entity_status_description         <chr> \"Struck Off\", \"Live Company\", \"Live …\n$ date                              <date> 2024-01-12, 2024-01-13, 2024-01-13,…\n$ uen_issue_date                    <date> 2024-01-12, 2024-01-13, 2024-01-13,…\n$ address_type                      <chr> \"LOCAL\", \"LOCAL\", \"LOCAL\", \"LOCAL\", …\n$ block                             <chr> \"781\", \"111\", \"111\", \"239\", \"1\", \"60…\n$ street_name                       <chr> \"BUKIT TIMAH ROAD\", \"SOMERSET ROAD\",…\n$ level_no                          <chr> \"na\", \"04\", \"04\", \"na\", \"04\", \"15\", …\n$ unit_no                           <chr> \"na\", \"01\", \"01\", \"na\", \"08\", \"01\", …\n$ building_name                     <chr> \"na\", \"111 SOMERSET\", \"111 SOMERSET\"…\n$ postal_code                       <chr> \"269759\", \"238164\", \"238164\", \"79946…\n$ other_address_line1               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ other_address_line2               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ account_due_date                  <chr> \"2026-07-31\", \"2026-07-31\", \"2026-07…\n$ annual_return_date                <chr> \"2025-04-07\", \"2025-07-14\", \"2025-07…\n$ primary_ssic_code                 <dbl> 86204, 86204, 86204, 86204, 86204, 8…\n$ primary_ssic_description          <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"DEALI…\n$ primary_user_described_activity   <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ YEAR                              <dbl> 2024, 2024, 2024, 2024, 2024, 2024, …\n$ MONTH_NUM                         <dbl> 1, 1, 1, 2, 3, 3, 4, 4, 2, 2, 4, 5, …\n$ MONTH_ABBR                        <ord> Jan, Jan, Jan, Feb, Mar, Mar, Apr, A…\n```\n\n\n:::\n:::\n\n\n\n**There are 81 observations we have retrieved for this analysis.**\n:::\n\n\n### 2.3 Geocoding\n\nWe will perform the following in this step: (Avoid doing so for \\> 5K datasets)\n\n-   Extract unique postal code from the poastal_code field of the tidied tibble data frame.\n-   Perform geocode by submitting the postal code to SLA OneMap Reverse Geocode API.\n-   Save the return results into 2 data frame namely *found* and *not_found*.\n\n::: panel-tabset\n## 9601\n\nBelow is to perform geocoding for the Laundry Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes_9601 <- unique(biz_9601$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound_9601 <- data.frame()\nnot_found_9601 <- data.frame(postcode_9601 = character())\n\nfor (pc_9601 in postcodes_9601) {\n  query_9601 <- list(\n    searchVal = pc_9601,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n  \n  res_9601 <- GET(url, query = query_9601)\n  json_9601 <- content(res_9601)\n  \n  if(json_9601$found != 0) {\n    df_9601 <- as.data.frame(json_9601$results, stringsAsFactors = FALSE)\n    df_9601$input_postcode_9601 <- pc_9601\n    found_9601 <- bind_rows(found_9601, df_9601)\n  } else{\n    not_found_9601 <- bind_rows(not_found_9601, data.frame(postcode_9601 = pc_9601))\n  }\n}\n```\n:::\n\n\n\n## 9602\n\nBelow is to perform geocoding for the Beauty Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes_9602 <- unique(biz_9602$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound_9602 <- data.frame()\nnot_found_9602 <- data.frame(postcode_9602 = character())\n\nfor (pc_9602 in postcodes_9602) {\n  query_9602 <- list(\n    searchVal = pc_9602,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n  res_9602 <- GET(url, query = query_9602)\n  json_9602 <- content(res_9602)\n  \n  if(json_9602$found != 0) {\n    df_9602 <- as.data.frame(json_9602$results, stringsAsFactors = FALSE)\n    df_9602$input_postcode_9602 <- pc_9602\n    found_9602 <- bind_rows(found_9602, df_9602)\n  } else{\n    not_found_9602 <- bind_rows(not_found_9602, data.frame(postcode_9602 = pc_9602))\n  }\n}\n```\n:::\n\n\n\n## 86204\n\nBelow is to perform geocoding for the Dental Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes_86204 <- unique(biz_86204$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound_86204 <- data.frame()\nnot_found_86204 <- data.frame(postcode_86204 = character())\n\nfor (pc_86204 in postcodes_86204) {\n  query_86204 <- list(\n    searchVal = pc_86204,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n  \n  res_86204 <- GET(url, query = query_86204)\n  json_86204 <- content(res_86204)\n  \n  if(json_86204$found != 0) {\n    df_86204 <- as.data.frame(json_86204$results, stringsAsFactors = FALSE)\n    df_86204$input_postcode_86204 <- pc_86204\n    found_86204 <- bind_rows(found_86204, df_86204)\n  } else{\n    not_found_86204 <- bind_rows(not_found_86204, data.frame(postcode_86204 = pc_86204))\n  }\n}\n```\n:::\n\n\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}