
project:
  type: website

website:
  title: "GeoSpatial"
  
  navbar:
    logo: "images/catgeo.png"
      
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Exercise 1a"
          href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.qmd
        - text: "Exercise 1b"
          href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.qmd
      - text: In-class Exercise
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
