
project:
  type: website

website:
  title: "GeoSpatial"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Exercise 1"
          href: Hands-on_Ex01.amd
        - text: "Exercise 2"
          href: Hands-on_Ex02.amd
      - text: In-class Exercise
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
