---
title: "01-Geospatial Data Science with R"
author: "Cathy C."
date: "Aug 23, 2025"
date-modified: "last-modified" #auto render date
format: html
execute: #how YML page work
  echo: true #will show code
  eval: true #will run code every time and show output
  warning: false #dont show warning msg
  freeze: true #controls rendering - no render if no changes
---

## Hands-on 01 Overview

## 1.1 Objectives

In this exercise, we will learn how to perform geospatial data science tasks in R by using **sf** package.

We aim to achieve the following competencies:

-   installing and loading [sf](https://r-spatial.github.io/sf/) and [tidyverse](https://www.tidyverse.org/) packages into R environment;
-   importing geospatial data by using appropriate functions of **sf** package;
-   importing aspatial data by using appropriate function of **readr** package;
-   exploring the content of simple feature data frame by using appropriate **Base R** and **sf** functions;
-   assigning or transforming coordinate systems by using using appropriate *sf* functions;
-   converting an aspatial data into a sf data frame by using appropriate function of **sf** package;
-   performing geoprocessing tasks by using appropriate functions of **sf** package;
-   performing data wrangling tasks by using appropriate functions of **dplyr** package and
-   performing Exploratory Data Analysis (EDA) by using appropriate functions from **ggplot2** package.

## 1.2 Data Acquisition

We will extract data sets for this exercise from the following sources:

-   Master Plan 2014 Subzone Boundary (Web) from [data.gov.sg](https://data.gov.sg/)
-   Pre-Schools [Location](https://data.gov.sg/datasets?query=preschool&resultId=d_61eefab99958fd70e6aab17320a71f1c&page=1) from [data.gov.sg](https://data.gov.sg/)
-   Cycling Path from [LTADataMall](https://www.mytransport.sg/content/mytransport/home/dataMall.html)
-   Latest version of Singapore Airbnb listing data from [Inside Airbnb](http://insideairbnb.com/get-the-data.html)

### 1.2.1 Extracting the geospatial data sets

### 1.2.2 Extracting the aspatial data set

## 1.3 Getting Started

## 1.4 Importing Geospatial Data

### 1.4.1 Importing polygon feature data in shapefile format

### 1.4.2 Importing polyline feature data in shapefile form

### 1.4.3 Importing GIS data in kml format

## 1.5 Checking the Content of A Simple Feature Data Frame

### 1.5.1 **Working with *st_geometry()***

### 1.5.2

## 1.6

## 1.7

### 1.7.1

### 1.7.2

## 1.8

### 1.8.1

### 1.8.2

## 1.9

### 1.9.1

### 1.9.2
