---
title: "07 - Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method"
author: "Cathy C."
date: "Oct 17, 2025"
date-modified: "last-modified" #auto render date
format: html
execute: #how YML page work
  echo: true #will show code
  eval: true #will run code every time and show output
  warning: false #dont show warning msg
  freeze: true #controls rendering - no render if no changes
---

## 1 Overview

**Geographically weighted regression (GWR)** is a spatial statistical technique that takes non-stationary variables into consideration (e.g., climate; demographic factors; physical environment characteristics) and models the local relationships between these independent variables and an outcome of interest (also known as dependent variable). In this hands-on exercise, we will build [hedonic pricing](https://www.investopedia.com/terms/h/hedonicpricing.asp) models by using GWR methods. The dependent variable is the resale prices of condominium in 2015. The independent variables are divided into either structural and locational.

::::: markgoals
::: markgoals-header
**Note**
:::

::: markgoals-container
**Non-stationary variables** = Things that change depending on where you are.

The two types of factors:

-   **Structural factors** - Physical features of the condo itself (size, number of rooms, age of building, facilities)
-   **Locational factors** - Where the condo is located (distance to MRT station, nearby schools, shopping centers)

**Hedonic pricing** = identifies price factors based on the idea that a good's price is influenced by both its internal characteristics and external factors. Hedonic pricing is often used to estimate the [value](https://www.investopedia.com/articles/trading/09/quant-strategies.asp) of environmental or ecosystem services that influence home prices. This valuation method often requires statistical expertise and model specification after collecting data.
:::
:::::

## 2 Getting started

## 3 About GWmodel

## 4 The data 

### 4.1 Data set

### 4.2 Geospatial data wrangling

#### 4.2.1 Import geospatial data

#### 4.2.2 Update CRS information

### 4.3 Aspatial data wrangling

#### 4.3.1 Import aspatial data

#### 4.3.2 Convert aspatial data frame into a sf object

## 5 Exploratory data analysis (EDA)

### 5.1 EDA using statistical graphics

### 5.2 Multiple histogram plots distributions of variables

### 5.3 Draw statistical point map

## 6 Hedonic pricing modelling in R

### 6.1 Simple linear regression method

### 6.2 Multiple linear regression method

### 6.3 **Building a hedonic pricing model using multiple linear regression method**

### 6.4 **Revising the model**

### 6.5 **Preparing Publication Quality Table: gtsummary method**

### 6.6 **Regression Diagnostics**

#### 6.6.1 Multicollinearity test

#### 6.6.2 Test for Non-Linearity

#### 6.6.3 Test for Normality Assumption

#### 6.6.4 Test for Spatial Autocorrelation

## **7 Building Hedonic Pricing Models using GWmodel**

### 7.1 **Building Fixed Bandwidth GWR Model** 

#### 7.1.1 Computing fixed bandwidth

#### 7.1.2 GWModel method - fixed bandwidth

### 7.2 **Building Adaptive Bandwidth GWR Model**

#### 7.2.1 Computing the adaptive bandwidth

#### 7.2.2 Constructing the adaptive bandwidth gwr model

### 7.3 **Visualising GWR Output**

### 7.4 **Converting SDF into *sf* data.frame**

### 7.5 **Visualising local R2**

### 7.6 **Visualising coefficient estimates**

## References
