---
title: "03 - Spatio-Temporal Point Patterns Analysis"
author: "Cathy C."
date: "Sep 9, 2025"
date-modified: "last-modified" #auto render date
format: html
execute: #how YML page work
  echo: true #will show code
  eval: true #will run code every time and show output
  warning: false #dont show warning msg
  freeze: true #controls rendering - no render if no changes
---

## Overview

A **spatio-temporal point process** (also called space-time or spatial-temporal point process) is a **random collection of points**, where each point represents the **time** and **location** of an event. Examples of events include incidence of disease, sightings or births of a species, or the occurrences of fires, earthquakes, lightning strikes, tsunamis, or volcanic eruptions.

The analysis of spatio-temporal point patterns is becoming increasingly necessary, given the rapid emergence of geographically and temporally indexed data in a wide range of fields. Several spatio-temporal point patterns analysis methods have been introduced and implemented in R in the last ten years.

In this exercise, various R packages will be combined to run a set of **spatio-temporal point pattern analyses**.

A real world forest fire events in Kepulauan Bangka Belitung, Indonesia from 1st January 2023 to 31st December 2023 is used to illustrate the methods, procedures and interpretations.

## 1 Objectives

Specific questions we would like to answer are:

-   are the locations of forest fire in Kepulauan Bangka Belitung spatial and spatio-temporally **independen**t?

-   if the answer is NO, **where and when** the observed forest fire locations tend to cluster?

## 2 The data

For the purpose of this exercise, two data sets will be used, they are:

-   *forestfires*, a csv file provides locations of forest fire detected from the Moderate Resolution Imaging Spectroradiometer (MODIS) sensor data. The data are downloaded from [Fire Information for Resource Management System](https://firms.modaps.eosdis.nasa.gov/download/). Only forest fires within Kepulauan Bangka Belitung will be used for this exercise.

-   *Kepulauan_Bangka_Belitung*, an **ESRI** **shapefile** showing the sub-district (i.e. [kelurahan](https://en.wikipedia.org/wiki/Villages_of_Indonesia)) boundary of Kepulauan Bangka Belitung. The data set was downloaded from [Indonesia Geospatial](https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html) portal. The original data covers the whole Indonesia. Only sub-districts within Kepulauan Bangka Belitung are extracted for this exercise.

## 3 Installing and Loading the R packages

## 4 Importing and Preparing Study Area

## 5 Importing and Preparing Forest Fire data

## 6 Visualising the Fire Points

## 7 Computing STKDE by Month

## 8 Computing STKDE by Day of Year

## 9 Computing STKDE by Day of Year: Improved method
