{
  "hash": "e17e82490aa1905d54baceaa05a1c05e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"04 - Spatial Weights and Applications\"\nauthor: \"Cathy C.\"\ndate: \"Sep 17, 2025\"\ndate-modified: \"last-modified\" #auto render date\nformat: html\nexecute: #how YML page work\n  echo: true #will show code\n  eval: true #will run code every time and show output\n  warning: false #dont show warning msg\n  freeze: true #controls rendering - no render if no changes\n---\n\n\n\n\n## Overview\n\nStarting from this, we will work on spatial weights and applications. In this exercise, we will learn how to compute spatial weights using R.\n\n## 1 Objectives\n\nWe will use the the ppropriate function(s) of below packages to achieve various tasks & goals.\n\n| Package   | Task                                                           |\n|-------------------------|-----------------------------------------------|\n| **sf**    | Import geospatial data                                         |\n| **readr** | Import csv file                                                |\n| **dplyr** | Perform relational join                                        |\n| **spdep** | Compute spatial weights & calculate spatially lagged variables |\n\n## 2 The Study Area and Data\n\nTwo data sets will be used in this hands-on exercise, they are:\n\n-   Hunan county boundary layer. This is a geospatial data set in ESRI shapefile format.\n\n-   *Hunan_2012.csv*: This csv file contains selected Hunan’s local development indicators in 2012.\n\n### 2.1 Getting started\n\nFirst we will install the necessary packages or ensure they are installed.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse, knitr)\n```\n:::\n\n\n\n\n### 2.2 Getting data into R environment\n\nThe geospatial data is in **ESRI shapefile** format and the attribute table is in **csv fomat**. We will bring the geospatial data and its associated attribute table into R environment.\n\n#### [**2.2.1 Import shapefile into R environment**]{style=\"color: #7D8D86;\"}\n\nBelow we use [*st_read()*](https://r-spatial.github.io/sf/reference/st_read.html) of **sf** package to import Hunan shapefile into R. The imported shapefile will be **simple features** Object of **sf**.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `/Users/cathyc/Documents/cathyschu/ISSS626GEO/Hands-on_Ex/Hands-on_Ex04/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n\n#### [**2.2.2 Import csv file into R environment & Performing relational join**]{style=\"color: #7D8D86;\"}\n\nUse *read_csv()* of **readr** package to import *Hunan_2012.csv*. The output will be R dataframe class.\n\nThen, use *left_join* from **dplyr** package to update the attribute table ofHunan's SpatialPolygonsDataFrame with the attribute fields of *hunan2012* dataframe.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n\nhunan <- left_join(hunan, hunan2012) %>% #this match by county\n  select(1:4, 7, 15) #keep county info and GDPPC\n```\n:::\n\n\n\n\n## 3 Visualising Regional Development Indicator\n\nPrepare a basemap and a choropleth map that shows the distribution of GDPPC 2012 by using `qtm()` from **tmap** package.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbasemap <- tm_shape(hunan) +\n  tm_polygons() +\n  tm_text(\"NAME_3\", size = 0.5) +\n  tm_layout(bg.color = \"#BBDCE5\", main.title = \"Hunan Basemap\")\n\ngdppc <- qtm(hunan, \"GDPPC\") +\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"),\n    bg.color = \"#BBDCE5\", main.title = \"GDP Per Capita\"\n  )\ntmap_arrange(basemap, gdppc, asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n## 4 Computing Contiguity Spatial Weights\n\nWe will use [*poly2nb()*](https://r-spatial.github.io/spdep/reference/poly2nb.html) of **spdep** package to compute **contiguity weight matrices** for the study area.\n\n[*poly2nb()*](https://r-spatial.github.io/spdep/reference/poly2nb.html) builds a neighbours list based on regions with contiguous boundaries.\n\nThe documentation says that you can pass a “queen” argument that takes TRUE or FALSE as options where the default is set to TRUE. And then this function will return a list of first order neighbours using the Queen criteria.\n\n### 4.1 **Computing (QUEEN) contiguity based neighbours**\n\nLet's compute Queen contiguity weight matrix.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, queen = TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n\n\n::::: markgoals\n::: markgoals-header\n**Learning**\n:::\n\n::: markgoals-container\nThe summary report above shows that there are **88 area units** in Hunan. The most connected area unit has **11 neighbours**. There are two area units with only one heighbours.\n:::\n:::::\n\nFor each polygon in the polygon object, `wm_q` lists all neighboring polygons. For example, to see the neighbors for the first polygon in the object, type:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2  3  4 57 85\n```\n\n\n:::\n:::\n\n\n\n\n::::: markgoals\n::: markgoals-header\n**Learning**\n:::\n\n::: markgoals-container\nThis means Polygon 1 has 5 neighbours. The numbers represent the polygon IDs stored in [hunan SpatialPolygonsDataFrame]{style=\"color: #BA487F;\"} class.\n:::\n:::::\n\nWe can also retrieve the country name of Polygon ID = 1 below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan$County[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Anxiang\"\n```\n\n\n:::\n:::\n\n\n\n\nAbove output shows that Polygon ID = 1 is Anxiang county.\n\nTo reveal the names of the 5 neighbours, we use `hunan$NAME_3`. [NAME_3]{style=\"color: #BA487F;\"} is the County name column in [hunan]{style=\"color: #BA487F;\"}.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan$NAME_3[c(2,3,4,57,85)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Hanshou\" \"Jinshi\"  \"Li\"      \"Nan\"     \"Taoyuan\"\n```\n\n\n:::\n:::\n\n\n\n\nWe can also retrieve the GDPPC of the 5 counties. Here is how:\n\n1.  retreieve IDs of the neighbours\n2.  retrieve their GDPPC from hunan using the IDs\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb1 <- wm_q[[1]]\nnb1 <- hunan$GDPPC[nb1]\nnb1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20981 34592 24473 21311 22879\n```\n\n\n:::\n:::\n\n\n\n\nThe printed output shows the GDPPC of these 5 nearest neighbours based on Queen's method.\n\nWe can also display the complete weight matrix by using `str()`. As it shows there are 88 lists (counties).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 88\n $ : int [1:5] 2 3 4 57 85\n $ : int [1:5] 1 57 58 78 85\n $ : int [1:4] 1 4 5 85\n $ : int [1:4] 1 3 5 6\n $ : int [1:4] 3 4 6 85\n $ : int [1:5] 4 5 69 75 85\n $ : int [1:4] 67 71 74 84\n $ : int [1:7] 9 46 47 56 78 80 86\n $ : int [1:6] 8 66 68 78 84 86\n $ : int [1:8] 16 17 19 20 22 70 72 73\n $ : int [1:3] 14 17 72\n $ : int [1:5] 13 60 61 63 83\n $ : int [1:4] 12 15 60 83\n $ : int [1:3] 11 15 17\n $ : int [1:4] 13 14 17 83\n $ : int [1:5] 10 17 22 72 83\n $ : int [1:7] 10 11 14 15 16 72 83\n $ : int [1:5] 20 22 23 77 83\n $ : int [1:6] 10 20 21 73 74 86\n $ : int [1:7] 10 18 19 21 22 23 82\n $ : int [1:5] 19 20 35 82 86\n $ : int [1:5] 10 16 18 20 83\n $ : int [1:7] 18 20 38 41 77 79 82\n $ : int [1:5] 25 28 31 32 54\n $ : int [1:5] 24 28 31 33 81\n $ : int [1:4] 27 33 42 81\n $ : int [1:3] 26 29 42\n $ : int [1:5] 24 25 33 49 54\n $ : int [1:3] 27 37 42\n $ : int 33\n $ : int [1:8] 24 25 32 36 39 40 56 81\n $ : int [1:8] 24 31 50 54 55 56 75 85\n $ : int [1:5] 25 26 28 30 81\n $ : int [1:3] 36 45 80\n $ : int [1:6] 21 41 47 80 82 86\n $ : int [1:6] 31 34 40 45 56 80\n $ : int [1:4] 29 42 43 44\n $ : int [1:4] 23 44 77 79\n $ : int [1:5] 31 40 42 43 81\n $ : int [1:6] 31 36 39 43 45 79\n $ : int [1:6] 23 35 45 79 80 82\n $ : int [1:7] 26 27 29 37 39 43 81\n $ : int [1:6] 37 39 40 42 44 79\n $ : int [1:4] 37 38 43 79\n $ : int [1:6] 34 36 40 41 79 80\n $ : int [1:3] 8 47 86\n $ : int [1:5] 8 35 46 80 86\n $ : int [1:5] 50 51 52 53 55\n $ : int [1:4] 28 51 52 54\n $ : int [1:5] 32 48 52 54 55\n $ : int [1:3] 48 49 52\n $ : int [1:5] 48 49 50 51 54\n $ : int [1:3] 48 55 75\n $ : int [1:6] 24 28 32 49 50 52\n $ : int [1:5] 32 48 50 53 75\n $ : int [1:7] 8 31 32 36 78 80 85\n $ : int [1:6] 1 2 58 64 76 85\n $ : int [1:5] 2 57 68 76 78\n $ : int [1:4] 60 61 87 88\n $ : int [1:4] 12 13 59 61\n $ : int [1:7] 12 59 60 62 63 77 87\n $ : int [1:3] 61 77 87\n $ : int [1:4] 12 61 77 83\n $ : int [1:2] 57 76\n $ : int 76\n $ : int [1:5] 9 67 68 76 84\n $ : int [1:4] 7 66 76 84\n $ : int [1:5] 9 58 66 76 78\n $ : int [1:3] 6 75 85\n $ : int [1:3] 10 72 73\n $ : int [1:3] 7 73 74\n $ : int [1:5] 10 11 16 17 70\n $ : int [1:5] 10 19 70 71 74\n $ : int [1:6] 7 19 71 73 84 86\n $ : int [1:6] 6 32 53 55 69 85\n $ : int [1:7] 57 58 64 65 66 67 68\n $ : int [1:7] 18 23 38 61 62 63 83\n $ : int [1:7] 2 8 9 56 58 68 85\n $ : int [1:7] 23 38 40 41 43 44 45\n $ : int [1:8] 8 34 35 36 41 45 47 56\n $ : int [1:6] 25 26 31 33 39 42\n $ : int [1:5] 20 21 23 35 41\n $ : int [1:9] 12 13 15 16 17 18 22 63 77\n $ : int [1:6] 7 9 66 67 74 86\n $ : int [1:11] 1 2 3 5 6 32 56 57 69 75 ...\n $ : int [1:9] 8 9 19 21 35 46 47 74 84\n $ : int [1:4] 59 61 62 88\n $ : int [1:2] 59 87\n - attr(*, \"class\")= chr \"nb\"\n - attr(*, \"region.id\")= chr [1:88] \"1\" \"2\" \"3\" \"4\" ...\n - attr(*, \"call\")= language poly2nb(pl = hunan, queen = TRUE)\n - attr(*, \"type\")= chr \"queen\"\n - attr(*, \"snap\")= num 9e-08\n - attr(*, \"sym\")= logi TRUE\n - attr(*, \"ncomp\")=List of 2\n  ..$ nc     : int 1\n  ..$ comp.id: int [1:88] 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\n\n\n### 4.2 **Creating (ROOK) contiguity based neighbours**\n\nNext we will compute Rook contiguity weight matrix.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_r <- poly2nb(hunan, queen = FALSE)\nsummary(wm_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 440 \nPercentage nonzero weights: 5.681818 \nAverage number of links: 5 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 10 \n 2  2 12 20 21 14 11  3  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 10 links\n```\n\n\n:::\n:::\n\n\n\n\n::::: markgoals\n::: markgoals-header\n**Learning**\n:::\n\n::: markgoals-container\n-   The report shows there are 88 areas in Hunan.\n\n-   The most connected area unit has 10 neighbours.\n\n-   There are 2 area units with only one neighbour.\n:::\n:::::\n\n### 4.3 **Visualising contiguity weights**\n\nTo visualise contiguity weights, we use connectivity graph. We will get the longitude and latitude of the Polygon Centroids. We will use a mapping function to get the coordinates in a separate data frame.\n\nThe mapping function applies a given function to each element of a vector and returns a vector of the same length. The input is the geometry column of `us.bound` and the function is `st_centroid`.\n\nWe will also use `map_dbl` variation of map from the **purrr** package.\n\n1.  Get longitude values: map the st_centroid function over the geometry column of us.bound and access the longitude value through double bracket notation [\\[\\[\\]\\] and 1]{style=\"color: #BA487F;\"}. This allows us to get the longitude.\n2.  Use the same method for latitude with \\[\\[2\\]\\].\n3.  Use [cbind]{style=\"color: #BA487F;\"} to put longitude and latitude into the same object.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlongitutde <- map_dbl(hunan$geometry, ~st_centroid(.x)[[1]])\n\nlatitude <- map_dbl(hunan$geometry, ~st_centroid(.x)[[2]])\n\ncoords <- cbind(longitutde, latitude)\n```\n:::\n\n\n\n\n4.  Check the first few observations to see if they were formatted correctly.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(coords)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     longitutde latitude\n[1,]   112.1531 29.44362\n[2,]   112.0372 28.86489\n[3,]   111.8917 29.47107\n[4,]   111.7031 29.74499\n[5,]   111.6138 29.49258\n[6,]   111.0341 29.79863\n```\n\n\n:::\n:::\n\n\n\n\n### 4.3.1 Queen contiguity vs Rook contiguity\n\nHover over two tabs and click to see the differences.\n\n::: panel-tabset\n## Queen contiguity based neighbours map\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#D0DDD0\")\nplot(hunan$geometry, border = \"grey\")\nplot(wm_q, coords, pch = 20, cex = 0.6, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-14-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Rook contiguity based neighbours map\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#D0DDD0\")\nplot(hunan$geometry, border = \"grey\")\nplot(wm_r, coords, pch = 20, cex = 0.6, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-15-1.png){width=1152}\n:::\n:::\n\n\n\n:::\n\n### 4.3.1 Queen contiguity vs Rook contiguity Comparison\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(1,2), bg = \"#D0DDD0\")\nplot(hunan$geometry, border = \"grey\", main = \"Queen Contiguity\")\nplot(wm_q, coords, pch = 18, cex = 0.6, add = TRUE, col = \"red\")\nplot(hunan$geometry, border = \"grey\", main = \"Rook Contiguity\")\nplot(wm_r, coords, pch = 18, cex = 0.6, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n## 5 Computing distance based neighbours\n\nIn this section, we will derive distance-based weight matrices by using [*dnearneigh()*](https://r-spatial.github.io/spdep/reference/dnearneigh.html) of **spdep** package. The function creates **distance-based neighbor relationships** for spatial analysis by identifying which geographic areas are \"neighbors\" based on distance ranges.\n\n-   It will set a distance band with **lower (d1)** and **upper (d2)** bounds using the `bounds=` argument. Areas within this distance range become neighbors.\n\n-   For distance calculation, the **projected coordinates** uses Euclidean (straight-line) distance. The **geographic coordinates** (with `longlat=TRUE`) uses great circle distance in **km**, accounting for Earth's curvature via WGS84 ellipsoid.\n\n-   An example is with d1=5 and d2=20, each region considers only areas between 5-20 km away as neighbors.\n\n### 5.1 **Determine the cut-off distance**\n\nThis step finds the **maximum distance** for the distance band.\n\n[**1: Find k-nearest neighbors**]{style=\"color: #84994F;\"}\\\n`knearneigh()` finds the k closest neighbors for each area. Returns a matrix showing which areas are neighbors.\n\n[**2: Convert to neighbor list**]{style=\"color: #84994F;\"}\\\n`knn2nb()` converts the matrix into a more usable list format. Each area gets a list of its neighbor IDs.\n\n[**3: Calculate actual distances**]{style=\"color: #84994F;\"}\\\n\n`nbdists()` measures the real distances between each area and its neighbors. Units meters/km for projected coordinates, km for lat/lon coordinates.\n\n[**4: Flatten the data**]{style=\"color: #84994F;\"}\\\n`unlist()` converts the nested list structure into a simple vector of all distances.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk1 <- knn2nb(knearneigh(coords))\nk1dists <- unlist(nbdists(k1, coords, longlat = TRUE))\nsummary(k1dists)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  24.79   32.57   38.01   39.07   44.52   61.79 \n```\n\n\n:::\n:::\n\n\n\n\n::::: markgoals\n::: markgoals-header\n**Learning**\n:::\n\n::: markgoals-container\nAbove summary report shows that the largest first nearest neighbour distance is 61.79km, so using this as the upper threshold gives certainty that all units will have at least ONE neighbour.\n:::\n:::::\n\n### 5.2 **Computing fixed distance weight matrix**\n\nNext we use `dnearneigh()` to compute the distance weight matrix.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_d62 <- dnearneigh(coords, 0, 62, longlat = TRUE)\nwm_d62\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 324 \nPercentage nonzero weights: 4.183884 \nAverage number of links: 3.681818 \n```\n\n\n:::\n:::\n\n\n\n\n::::: markgoals\n::: markgoals-header\n**Learning**\n:::\n\n::: markgoals-container\n-   There are 88 polygons in the dataset.\n\n-   There are 324 pairs of regions that are considered neighbors.\n\n-   Out of all possible pairs of regions (88 × 88 = 7,744 total possible connections), only 4.18% are actually neighbors.\n\n-   On average, each region has about 3.68 neighbors\n:::\n:::::\n\n### 5.3 **Computing adaptive distance weight matrix**\n\n## 6 Weights based on IDW\n\n## 7 Row-standardised Weights Matrix\n\n## 8 Application of Spatial Weight Matrix\n\n### 8.1 **Spatial lag with row-standardized weights**\n\n### 8.2 **Spatial lag as a sum of neighboring values**\n\n### 8.3 **Spatial window average**\n\n### 8.4 **Spatial window sum**\n\n## 9 References\n",
    "supporting": [
      "Hands-on_Ex04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}