---
title: "09 - Modelling Geographical Accessibility"
author: "Cathy C."
date: "Nov 05, 2025"
date-modified: "last-modified" #auto render date
format: html
execute: #how YML page work
  echo: true #will show code
  eval: true #will run code every time and show output
  warning: false #dont show warning msg
  freeze: true #controls rendering - no render if no changes
---

## 1 Overview

We will learn to compute **Global Measures of Spatial Autocorrelation (GMSA)** by using **spdep** package. We will do the following in this hands-on exercise. - import geospatial data using appropriate function(s) of **sf** package - import csv file using appropriate function of readr package - perform relational join using appropriate join function of **dplyr** package - compute Global Spatial Autocorrelation (GSA) statistics using appropriate functions of **spdep** package, plot Moran scatterplot - compute and plot spatial correlogram using appropriate function of **spdep** package - provide statistically correct interpretation of GSA statistics.

## 2 The data


## 3 Getting started

## 4 Geospatial Data Wrangling

### 4.1 Importing geospatial data

### 4.2 Updating CRS information

### 4.3 Cleaning and updating attribute fields of the geospatial data


## 5 Apsaital Data Handling and Wrangling

### 5.1 Importing Distance Matrix


### 5.2 Tidying distance matrix


## 6 Modelling and Visualising Accessibility using Hansen Method

### 6.1 Computing Hansen’s accessibility

### 6.2 Visualising Hansen’s accessibility

### 6.3 Statistical graphic visualisation

## 7 Modelling and Visualising Accessibility using KD2SFCA Method

### 7.1 Computing KD2SFCA’s accessibility

### 7.2 Visualising KD2SFCA’s accessibility

### 7.3 Statistical graphic visualisation

## 8 Modelling and Visualising Accessibility using Spatial Accessibility Measure (SAM) Method

### 8.1 Computing SAM accessibility

### 8.2 Visualising SAM’s accessibility

### 8.3 Statistical graphic visualisation



::::: markgoals
::: markgoals-header
**Note**
:::

::: markgoals-container
:::
:::::
