{
  "hash": "03f5b926370e7bf914b77fad8b2e5742",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise: Public Good\"\nauthor: \"Cathy C.\"\ndate: \"Sep 17, 2025\"\ndate-modified: \"last-modified\" #auto render date\nformat: html\nexecute: #how YML page work\n  echo: true #will show code\n  eval: true #will run code every time and show output\n  warning: false #dont show warning msg\n  freeze: true #controls rendering - no render if no changes\n  cache: true\n---\n\n\n\n\n## Introduction\n\nIn this study, we are interested in understanding the spatial and spatio-temporal patterns of new businesses and firms established in Singapore. Based on the Singapore Standard Industrial Classification 2020, there are over 1,500 business types. Among these, we will focus on **Laundry services** (including Laundry and dry cleaning services and self-operated laundries), **Beauty services** (including Hairdressing salons/shops, beauty salons and spas, as well as manicure and pedicure services, and **Dental services**.\n\nThe 3 chosen businesses are essential for working adults / professionals to take care of self for outlook and health. We would like to observe how these activities evolve and potentially to enhance quality of life and well-being.\n\nWe will start from processing the data, perform Kernel Density Estimation, Clarke-Evans test, and then conduct analysis with visualisation and test results. First-order and second-order spatial and spatio-temporal analyses are conducted to understand the overall new businesses and their temporal patterns during the period of time Jan 2024 to June 2025.\n\nDue to data set sizes, we will analyse spatial patterns by quarter for Laundry Services and Dental Services, and by month for Beauty Services. Different spatial point pattern testing menthods are used to analyse the 3 business types: G-function for Dental Services, L-function for Beauty Services, and F-function for Laundry Services.\n\n## 1 Loading the R package\n\nWe will use **tidyverse, sf, tmap, tmap,** and **httr** packages to process data sets, along with other packages for computing KDE and plotting visualisations.\n\n| R Package | Purpose |\n|------------------|------------------------------------------------------|\n| **tidyverse** | the **tidyverse** package is designed to make it easy to install and load core packages from the tidyverse in a single command. There are ggplot2, dplyr, tidyr, readr, purrr, and tibble, etc to manipulate, tidy, import, visualise data. |\n| **sf** | provides support for working with simple features, a standardized way to represent geographic vector data. It serves as a comprehensive tool for handling spatial data within the R environment. |\n| **tmap** | serves the purpose of creating thematic maps, offering a flexible and intuitive way to visualize spatial data. It is designed to produce both static and interactive maps using a consistent, layer-based syntax similar to `ggplot2`. |\n| **httr** | serves as a tool for interacting with web APIs and performing HTTP requests within the R environment. |\n| **knitr** | seamlessly integrate R code, its output (including text, tables, and graphics), and narrative text within a single document. |\n| **rvest** | simplify the process of scraping and manipulating web data. It allows for the extraction of information from websites and transforms it into a format suitable for analysis in R. |\n| **spatstat** | provides functions for spatial statistics with a strong focus on analysing spatial point patterns. |\n| **terra** | provides methods for manipulating geographic (spatial) data in both raster and vector formats. |\n| **raster** | provides functions which reads, writes, manipulates, analyses and model of gridded spatial data (i.e. raster). In this hands-on exercise, it will be used to convert image output generate by spatstat into raster format. |\n| **sparr** | provides a suite of functions for analyzing spatial and spatiotemporal point patterns, particularly focusing on the estimation and inference of relative risk surfaces. |\n\n: R Packages\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, sf, tmap, httr, knitr, rvest, spatstat, terra, raster, sparr)\n```\n:::\n\n\n\n\n## 2 The Data\n\nThere are mainly two raw public datasets used in this study.\n\n-   **ACRA (Accounting and Corporate Regulatory Authority) Information on Corporate Entities datasets**: contains the business entities information, including their names, registration, status, and location.\n-   **The Master Plan 2019 Boundary**: consists of the geographical boundary of Singapore at the planning subzone level. The data is based on URA Master Plan 2019.\n-   **Singapore Residents by Planning Area / Subzone, Age Group, Sex and Type of Dwelling, June 2024**: *respopagesextod2024.csv* is an aspatial data fie. It can be downloaded at Department of Statistics, Singapore.\n\n### 2.1 Importing ACRA data\n\nWe downloaded the ACRA (Accounting and Corporate Regulatory Authority) Information on Corporate Entities datasets from data.gov.sg, and will import the ACRA data and transform them as tibble frame.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfolder_path <- \"data/aspatial/acra\"\nfile_list <- list.files(path = folder_path,\n                        pattern = \"^ACRA*.*\\\\.csv$\",\n                        full.names = TRUE)\nacra_data <- file_list %>%\n  map_dfr(read_csv) #import and append all of them together!!\n```\n:::\n\n\n\n\nThen, we will write the data into .rds to store it in the data folder. This is so no need to process data every time.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(acra_data, \"data/rds/acra_data.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacra_data <- read_rds(\"data/rds/acra_data.rds\")\n```\n:::\n\n\n\n\n### 2.2 Tidying ACRA data\n\nWith this step, we will extract the business codes 9601, 9602, and 86204, then rename the columns and transform the data type necessarily.\n\nThe business types chosen are:\n\n| Business Code | Types / subtypes |\n|----------------------|--------------------------------------------------|\n| **9601** | **Washing and (Dry-) Cleaning of Textile and Fur Products** |\n| 96011 | Laundry and dry cleaning services except self-operated laundries |\n| 96012 | Self-operated laundries |\n| **9602** | **Hairdressing, Beauty and Other Personal Care Services** |\n| 96021 | Hairdressing salons/shops (including barber shops) |\n| 96022 | Beauty salons and spas (including slimming, skin care and hair care centres) |\n| 96023 | Manicure and pedicure services |\n| **86024** | **Dental services** |\n\n: Business Code & Types\n\nWe use below code to retrieve the data between Jan 1, 2024 to June 30, 2025 for the 3 different major business types.\n\n::: panel-tabset\n## 9601\n\n**Washing and (Dry-) Cleaning of Textile and Fur Products** Business Code 9601 encompasses Laundry cleaning and self-operated laundries (96011 & 96012)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601 <- acra_data %>%\n  dplyr::select(1:24) %>%\n  filter(primary_ssic_code == 96011 | primary_ssic_code == 96012) %>%\n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         YEAR = year(date),\n         MONTH_NUM = month(date),\n         MONTH_ABBR = month(date, label = TRUE, abbr = TRUE)) %>% #this gives Jan, Feb, Mar...\n  mutate(postal_code = str_pad(postal_code,\n                               width = 6, side = \"left\", pad = \"0\")) %>% #if missing digits, will replace with zero.\nfilter(YEAR == 2024 | YEAR == 2025 & MONTH_NUM <= 6)\n\nglimpse(biz_9601)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 150\nColumns: 27\n$ uen                               <chr> \"202401518M\", \"202409043N\", \"2025075…\n$ issuance_agency_id                <chr> \"ACRA\", \"ACRA\", \"ACRA\", \"ACRA\", \"ACR…\n$ entity_name                       <chr> \"ALL DAY EVERYDAY PTE. LTD.\", \"ABEND…\n$ entity_type_description           <chr> \"Local Company\", \"Local Company\", \"L…\n$ business_constitution_description <chr> \"na\", \"na\", \"na\", \"na\", \"Sole-Propri…\n$ company_type_description          <chr> \"Exempt Private Company Limited by S…\n$ paf_constitution_description      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ entity_status_description         <chr> \"Live Company\", \"Live Company\", \"Liv…\n$ date                              <date> 2024-01-10, 2024-03-07, 2025-02-20,…\n$ uen_issue_date                    <date> 2024-01-10, 2024-03-07, 2025-02-20,…\n$ address_type                      <chr> \"LOCAL\", \"LOCAL\", \"LOCAL\", \"LOCAL\", …\n$ block                             <chr> \"105\", \"138\", \"7030\", \"160\", \"842G\",…\n$ street_name                       <chr> \"BISHAN STREET 12\", \"JOO SENG ROAD\",…\n$ level_no                          <chr> \"05\", \"02\", \"02\", \"14\", \"14\", \"na\", …\n$ unit_no                           <chr> \"242\", \"02\", \"11\", \"04\", \"86\", \"na\",…\n$ building_name                     <chr> \"BISHAN VIEW\", \"na\", \"NORTHSTAR @ AM…\n$ postal_code                       <chr> \"570105\", \"368361\", \"569880\", \"06891…\n$ other_address_line1               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ other_address_line2               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ account_due_date                  <chr> \"2026-07-31\", \"2026-07-31\", \"2026-08…\n$ annual_return_date                <chr> \"2025-06-29\", \"2025-07-01\", \"na\", \"n…\n$ primary_ssic_code                 <dbl> 96012, 96011, 96011, 96012, 96012, 9…\n$ primary_ssic_description          <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ primary_user_described_activity   <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ YEAR                              <dbl> 2024, 2024, 2025, 2025, 2024, 2025, …\n$ MONTH_NUM                         <dbl> 1, 3, 2, 6, 7, 4, 11, 1, 2, 5, 4, 4,…\n$ MONTH_ABBR                        <ord> Jan, Mar, Feb, Jun, Jul, Apr, Nov, J…\n```\n\n\n:::\n:::\n\n\n\n\n**There are 150 observations we have retrieved for this analysis.**\n\n## 9602\n\n**Hairdressing, Beauty and Other Personal Care Services** Business Code 9602 includes hair dressing, beauty salons and manicure & pedicure services.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602 <- acra_data %>%\n  dplyr::select(1:24) %>%\n  filter(primary_ssic_code == 96021 | primary_ssic_code == 96022 | primary_ssic_code == 96023) %>%\n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         YEAR = year(date),\n         MONTH_NUM = month(date),\n         MONTH_ABBR = month(date, label = TRUE, abbr = TRUE)) %>% #this gives Jan, Feb, Mar...\n  mutate(postal_code = str_pad(postal_code,\n                               width = 6, side = \"left\", pad = \"0\")) %>% #if missing digits, will replace with zero.\nfilter(YEAR == 2024 | YEAR == 2025 & MONTH_NUM <= 6)\n\nglimpse(biz_9602)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,762\nColumns: 27\n$ uen                               <chr> \"202400273N\", \"202400385D\", \"2024010…\n$ issuance_agency_id                <chr> \"ACRA\", \"ACRA\", \"ACRA\", \"ACRA\", \"ACR…\n$ entity_name                       <chr> \"A-VINZ (KV) PTE. LTD.\", \"ACTINIC VE…\n$ entity_type_description           <chr> \"Local Company\", \"Local Company\", \"L…\n$ business_constitution_description <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ company_type_description          <chr> \"Exempt Private Company Limited by S…\n$ paf_constitution_description      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ entity_status_description         <chr> \"Live Company\", \"Struck Off\", \"Live …\n$ date                              <date> 2024-01-02, 2024-01-02, 2024-01-06,…\n$ uen_issue_date                    <date> 2024-01-02, 2024-01-02, 2024-01-06,…\n$ address_type                      <chr> \"LOCAL\", \"LOCAL\", \"LOCAL\", \"LOCAL\", …\n$ block                             <chr> \"7030\", \"9\", \"67\", \"250\", \"1\", \"371\"…\n$ street_name                       <chr> \"ANG MO KIO AVENUE 5\", \"RAFFLES PLAC…\n$ level_no                          <chr> \"07\", \"19\", \"01\", \"19\", \"01\", \"B1\", …\n$ unit_no                           <chr> \"36\", \"21\", \"459\", \"03\", \"20\", \"60\",…\n$ building_name                     <chr> \"NORTHSTAR @ AMK\", \"REPUBLIC PLAZA\",…\n$ postal_code                       <chr> \"569880\", \"048619\", \"330067\", \"17910…\n$ other_address_line1               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ other_address_line2               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ account_due_date                  <chr> \"2026-07-31\", \"2025-07-31\", \"2026-07…\n$ annual_return_date                <chr> \"2025-07-30\", \"na\", \"2025-07-10\", \"2…\n$ primary_ssic_code                 <dbl> 96021, 96021, 96022, 96021, 96021, 9…\n$ primary_ssic_description          <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"BEAUT…\n$ primary_user_described_activity   <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ YEAR                              <dbl> 2024, 2024, 2024, 2024, 2024, 2024, …\n$ MONTH_NUM                         <dbl> 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, …\n$ MONTH_ABBR                        <ord> Jan, Jan, Jan, Jan, Jan, Jan, Feb, F…\n```\n\n\n:::\n:::\n\n\n\n\n**There are 1762 observations we have retrieved for this analysis.**\n\n## 86204\n\n**Dental services**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204 <- acra_data %>%\n  dplyr::select(1:24) %>%\n  filter(primary_ssic_code == 86204) %>%\n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         YEAR = year(date),\n         MONTH_NUM = month(date),\n         MONTH_ABBR = month(date, label = TRUE, abbr = TRUE)) %>% #this gives Jan, Feb, Mar...\n  mutate(postal_code = str_pad(postal_code,\n                               width = 6, side = \"left\", pad = \"0\")) %>% #if missing digits, will replace with zero.\nfilter(YEAR == 2024 | YEAR == 2025 & MONTH_NUM <= 6)\n\nglimpse(biz_86204)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 81\nColumns: 27\n$ uen                               <chr> \"202401990E\", \"202402057R\", \"2024020…\n$ issuance_agency_id                <chr> \"ACRA\", \"ACRA\", \"ACRA\", \"ACRA\", \"ACR…\n$ entity_name                       <chr> \"AZURE DENTAL PTE. LTD.\", \"ASTER DEN…\n$ entity_type_description           <chr> \"Local Company\", \"Local Company\", \"L…\n$ business_constitution_description <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ company_type_description          <chr> \"Exempt Private Company Limited by S…\n$ paf_constitution_description      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ entity_status_description         <chr> \"Struck Off\", \"Live Company\", \"Live …\n$ date                              <date> 2024-01-12, 2024-01-13, 2024-01-13,…\n$ uen_issue_date                    <date> 2024-01-12, 2024-01-13, 2024-01-13,…\n$ address_type                      <chr> \"LOCAL\", \"LOCAL\", \"LOCAL\", \"LOCAL\", …\n$ block                             <chr> \"781\", \"111\", \"111\", \"239\", \"1\", \"60…\n$ street_name                       <chr> \"BUKIT TIMAH ROAD\", \"SOMERSET ROAD\",…\n$ level_no                          <chr> \"na\", \"04\", \"04\", \"na\", \"04\", \"15\", …\n$ unit_no                           <chr> \"na\", \"01\", \"01\", \"na\", \"08\", \"01\", …\n$ building_name                     <chr> \"na\", \"111 SOMERSET\", \"111 SOMERSET\"…\n$ postal_code                       <chr> \"269759\", \"238164\", \"238164\", \"79946…\n$ other_address_line1               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ other_address_line2               <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ account_due_date                  <chr> \"2026-07-31\", \"2026-07-31\", \"2026-07…\n$ annual_return_date                <chr> \"2025-04-07\", \"2025-07-14\", \"2025-07…\n$ primary_ssic_code                 <dbl> 86204, 86204, 86204, 86204, 86204, 8…\n$ primary_ssic_description          <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"DEALI…\n$ primary_user_described_activity   <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", …\n$ YEAR                              <dbl> 2024, 2024, 2024, 2024, 2024, 2024, …\n$ MONTH_NUM                         <dbl> 1, 1, 1, 2, 3, 3, 4, 4, 2, 2, 4, 5, …\n$ MONTH_ABBR                        <ord> Jan, Jan, Jan, Feb, Mar, Mar, Apr, A…\n```\n\n\n:::\n:::\n\n\n\n\n**There are 81 observations we have retrieved for this analysis.**\n:::\n\n### 2.3 Geocoding\n\nWe will perform the following in this step: (Avoid doing so for \\> 5K datasets)\n\n-   Extract unique postal code from the poastal_code field of the tidied tibble data frame.\n-   Perform geocode by submitting the postal code to SLA OneMap Reverse Geocode API.\n-   Save the return results into 2 data frame namely *found* and *not_found*.\n\n::: panel-tabset\n## 9601\n\nBelow is to perform geocoding for the Laundry Services type.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes_9601 <- unique(biz_9601$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound_9601 <- data.frame()\nnot_found_9601 <- data.frame(postcode_9601 = character())\n\nfor (pc_9601 in postcodes_9601) {\n  query_9601 <- list(\n    searchVal = pc_9601,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n  \n  res_9601 <- GET(url, query = query_9601)\n  json_9601 <- content(res_9601)\n  \n  if(json_9601$found != 0) {\n    df_9601 <- as.data.frame(json_9601$results, stringsAsFactors = FALSE)\n    df_9601$input_postcode_9601 <- pc_9601\n    found_9601 <- bind_rows(found_9601, df_9601)\n  } else{\n    not_found_9601 <- bind_rows(not_found_9601, data.frame(postcode_9601 = pc_9601))\n  }\n}\n```\n:::\n\n\n\n\n## 9602\n\nBelow is to perform geocoding for the Beauty Services type.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes_9602 <- unique(biz_9602$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound_9602 <- data.frame()\nnot_found_9602 <- data.frame(postcode_9602 = character())\n\nfor (pc_9602 in postcodes_9602) {\n  query_9602 <- list(\n    searchVal = pc_9602,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n  res_9602 <- GET(url, query = query_9602)\n  json_9602 <- content(res_9602)\n  \n  if(json_9602$found != 0) {\n    df_9602 <- as.data.frame(json_9602$results, stringsAsFactors = FALSE)\n    df_9602$input_postcode_9602 <- pc_9602\n    found_9602 <- bind_rows(found_9602, df_9602)\n  } else{\n    not_found_9602 <- bind_rows(not_found_9602, data.frame(postcode_9602 = pc_9602))\n  }\n}\n```\n:::\n\n\n\n\n## 86204\n\nBelow is to perform geocoding for the Dental Services type.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes_86204 <- unique(biz_86204$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound_86204 <- data.frame()\nnot_found_86204 <- data.frame(postcode_86204 = character())\n\nfor (pc_86204 in postcodes_86204) {\n  query_86204 <- list(\n    searchVal = pc_86204,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n  \n  res_86204 <- GET(url, query = query_86204)\n  json_86204 <- content(res_86204)\n  \n  if(json_86204$found != 0) {\n    df_86204 <- as.data.frame(json_86204$results, stringsAsFactors = FALSE)\n    df_86204$input_postcode_86204 <- pc_86204\n    found_86204 <- bind_rows(found_86204, df_86204)\n  } else{\n    not_found_86204 <- bind_rows(not_found_86204, data.frame(postcode_86204 = pc_86204))\n  }\n}\n```\n:::\n\n\n\n:::\n\n### 2.4 Appending the location information\nIn this step, we will append the location information to the business entities based on their postal code.\n\n::: panel-tabset\n## 9601\nBelow is to perform location appendix for the Laundry Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601 = biz_9601 %>%\n  left_join(found_9601,\n            by = c('postal_code' = 'POSTAL'))\n```\n:::\n\n\n\n\n## 9602\nBelow is to perform location appendix for the Beauty Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602 = biz_9602 %>%\n  left_join(found_9602,\n            by = c('postal_code' = 'POSTAL'))\n```\n:::\n\n\n\n\n## 86204\nBelow is to perform location appendix for the Dental Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204 = biz_86204 %>%\n  left_join(found_86204,\n            by = c('postal_code' = 'POSTAL'))\n```\n:::\n\n\n\n:::\n\n\n### 2.5 Converting into SF data frame\nNow we will convert the tibble data frame to a `sf` object. \n::: panel-tabset\n## 9601\nBelow is to convert data type for the Laundry Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601_sf <- st_as_sf(biz_9601,\n                         coords = c(\"X\", \"Y\"),\n                         crs = 3414)\n```\n:::\n\n\n\n\n## 9602\nBelow is to convert data type for the Beauty Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602_sf <- st_as_sf(biz_9602,\n                         coords = c(\"X\", \"Y\"),\n                         crs = 3414)\n```\n:::\n\n\n\n\n## 86204\nBelow is to convert data type for the Dental Services type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204_sf <- st_as_sf(biz_86204,\n                         coords = c(\"X\", \"Y\"),\n                         crs = 3414)\n```\n:::\n\n\n\n:::\n\n**Take a look at the simple feature data (Laundry service).**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(biz_9601_sf))\n```\n\n::: {.cell-output-display}\n\n\n|uen        |issuance_agency_id |entity_name                |entity_type_description          |business_constitution_description |company_type_description                 |paf_constitution_description |entity_status_description |date       |uen_issue_date |address_type |block |street_name         |level_no |unit_no |building_name                        |postal_code |other_address_line1 |other_address_line2 |account_due_date |annual_return_date | primary_ssic_code|primary_ssic_description |primary_user_described_activity | YEAR| MONTH_NUM|MONTH_ABBR |SEARCHVAL                                         |BLK_NO |ROAD_NAME           |BUILDING                                          |ADDRESS                                                                              |LATITUDE         |LONGITUDE        |input_postcode_9601 |SEARCHVAL.1                          |BLK_NO.1 |ROAD_NAME.1         |BUILDING.1                           |ADDRESS.1                                                                      |POSTAL.1 |X.1              |Y.1              |LATITUDE.1       |LONGITUDE.1      |SEARCHVAL.2                         |BLK_NO.2 |ROAD_NAME.2         |BUILDING.2                          |ADDRESS.2                                                                     |POSTAL.2 |X.2              |Y.2              |LATITUDE.2       |LONGITUDE.2      |SEARCHVAL.3                                   |BLK_NO.3 |ROAD_NAME.3         |BUILDING.3                                    |ADDRESS.3                                                                               |POSTAL.3 |X.3              |Y.3              |LATITUDE.3       |LONGITUDE.3      |SEARCHVAL.4                      |BLK_NO.4 |ROAD_NAME.4         |BUILDING.4                       |ADDRESS.4                                                                  |POSTAL.4 |X.4              |Y.4              |LATITUDE.4       |LONGITUDE.4      |SEARCHVAL.5     |BLK_NO.5 |ROAD_NAME.5         |BUILDING.5      |ADDRESS.5                                                 |POSTAL.5 |X.5              |Y.5              |LATITUDE.5       |LONGITUDE.5      |SEARCHVAL.6 |BLK_NO.6 |ROAD_NAME.6 |BUILDING.6 |ADDRESS.6 |POSTAL.6 |X.6 |Y.6 |LATITUDE.6 |LONGITUDE.6 |SEARCHVAL.7 |BLK_NO.7 |ROAD_NAME.7 |BUILDING.7 |ADDRESS.7 |POSTAL.7 |X.7 |Y.7 |LATITUDE.7 |LONGITUDE.7 |SEARCHVAL.8 |BLK_NO.8 |ROAD_NAME.8 |BUILDING.8 |ADDRESS.8 |POSTAL.8 |X.8 |Y.8 |LATITUDE.8 |LONGITUDE.8 |SEARCHVAL.9 |BLK_NO.9 |ROAD_NAME.9 |BUILDING.9 |ADDRESS.9 |POSTAL.9 |X.9 |Y.9 |LATITUDE.9 |LONGITUDE.9 |geometry                  |\n|:----------|:------------------|:--------------------------|:--------------------------------|:---------------------------------|:----------------------------------------|:----------------------------|:-------------------------|:----------|:--------------|:------------|:-----|:-------------------|:--------|:-------|:------------------------------------|:-----------|:-------------------|:-------------------|:----------------|:------------------|-----------------:|:------------------------|:-------------------------------|----:|---------:|:----------|:-------------------------------------------------|:------|:-------------------|:-------------------------------------------------|:------------------------------------------------------------------------------------|:----------------|:----------------|:-------------------|:------------------------------------|:--------|:-------------------|:------------------------------------|:------------------------------------------------------------------------------|:--------|:----------------|:----------------|:----------------|:----------------|:-----------------------------------|:--------|:-------------------|:-----------------------------------|:-----------------------------------------------------------------------------|:--------|:----------------|:----------------|:----------------|:----------------|:---------------------------------------------|:--------|:-------------------|:---------------------------------------------|:---------------------------------------------------------------------------------------|:--------|:----------------|:----------------|:----------------|:----------------|:--------------------------------|:--------|:-------------------|:--------------------------------|:--------------------------------------------------------------------------|:--------|:----------------|:----------------|:----------------|:----------------|:---------------|:--------|:-------------------|:---------------|:---------------------------------------------------------|:--------|:----------------|:----------------|:----------------|:----------------|:-----------|:--------|:-----------|:----------|:---------|:--------|:---|:---|:----------|:-----------|:-----------|:--------|:-----------|:----------|:---------|:--------|:---|:---|:----------|:-----------|:-----------|:--------|:-----------|:----------|:---------|:--------|:---|:---|:----------|:-----------|:-----------|:--------|:-----------|:----------|:---------|:--------|:---|:---|:----------|:-----------|:-------------------------|\n|202401518M |ACRA               |ALL DAY EVERYDAY PTE. LTD. |Local Company                    |na                                |Exempt Private Company Limited by Shares |na                           |Live Company              |2024-01-10 |2024-01-10     |LOCAL        |105   |BISHAN STREET 12    |05       |242     |BISHAN VIEW                          |570105      |na                  |na                  |2026-07-31       |2025-06-29         |             96012|na                       |na                              | 2024|         1|Jan        |BISHAN VIEW                                       |105    |BISHAN STREET 12    |BISHAN VIEW                                       |105 BISHAN STREET 12 BISHAN VIEW SINGAPORE 570105                                    |1.34589493632505 |103.847365252767 |570105              |NA                                   |NA       |NA                  |NA                                   |NA                                                                             |NA       |NA               |NA               |NA               |NA               |NA                                  |NA       |NA                  |NA                                  |NA                                                                            |NA       |NA               |NA               |NA               |NA               |NA                                            |NA       |NA                  |NA                                            |NA                                                                                      |NA       |NA               |NA               |NA               |NA               |NA                               |NA       |NA                  |NA                               |NA                                                                         |NA       |NA               |NA               |NA               |NA               |NA              |NA       |NA                  |NA              |NA                                                        |NA       |NA               |NA               |NA               |NA               |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |POINT (29563.24 36447.74) |\n|202409043N |ACRA               |ABENDANCE PTE. LTD.        |Local Company                    |na                                |Exempt Private Company Limited by Shares |na                           |Live Company              |2024-03-07 |2024-03-07     |LOCAL        |138   |JOO SENG ROAD       |02       |02      |na                                   |368361      |na                  |na                  |2026-07-31       |2025-07-01         |             96011|na                       |na                              | 2024|         3|Mar        |138 JOO SENG ROAD SINGAPORE 368361                |138    |JOO SENG ROAD       |NIL                                               |138 JOO SENG ROAD SINGAPORE 368361                                                   |1.3377756933485  |103.884646509523 |368361              |NA                                   |NA       |NA                  |NA                                   |NA                                                                             |NA       |NA               |NA               |NA               |NA               |NA                                  |NA       |NA                  |NA                                  |NA                                                                            |NA       |NA               |NA               |NA               |NA               |NA                                            |NA       |NA                  |NA                                            |NA                                                                                      |NA       |NA               |NA               |NA               |NA               |NA                               |NA       |NA                  |NA                               |NA                                                                         |NA       |NA               |NA               |NA               |NA               |NA              |NA       |NA                  |NA              |NA                                                        |NA       |NA               |NA               |NA               |NA               |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |POINT (33712.25 35550.02) |\n|202507525N |ACRA               |AWESOME LAUNDRY PTE. LTD.  |Local Company                    |na                                |Exempt Private Company Limited by Shares |na                           |Live Company              |2025-02-20 |2025-02-20     |LOCAL        |7030  |ANG MO KIO AVENUE 5 |02       |11      |NORTHSTAR @ AMK                      |569880      |na                  |na                  |2026-08-31       |na                 |             96011|na                       |na                              | 2025|         2|Feb        |BANYAN TREE EDUCATION @ AMK                       |7030   |ANG MO KIO AVENUE 5 |BANYAN TREE EDUCATION @ AMK                       |7030 ANG MO KIO AVENUE 5 BANYAN TREE EDUCATION @ AMK SINGAPORE 569880                |1.37792345221534 |103.875389838376 |569880              |DISCOVERY PLANET LIMITED PARTNERSHIP |7030     |ANG MO KIO AVENUE 5 |DISCOVERY PLANET LIMITED PARTNERSHIP |7030 ANG MO KIO AVENUE 5 DISCOVERY PLANET LIMITED PARTNERSHIP SINGAPORE 569880 |569880   |32682.0063954461 |39989.3313855752 |1.37792345221534 |103.875389838376 |ESHKOL VALLEY @ NORTHSTAR PTE. LTD. |7030     |ANG MO KIO AVENUE 5 |ESHKOL VALLEY @ NORTHSTAR PTE. LTD. |7030 ANG MO KIO AVENUE 5 ESHKOL VALLEY @ NORTHSTAR PTE. LTD. SINGAPORE 569880 |569880   |32682.0063954461 |39989.3313855752 |1.37792345221534 |103.875389838376 |LITTLE FOOTPRINTS SCHOOLHOUSE (AMK) PTE. LTD. |7030     |ANG MO KIO AVENUE 5 |LITTLE FOOTPRINTS SCHOOLHOUSE (AMK) PTE. LTD. |7030 ANG MO KIO AVENUE 5 LITTLE FOOTPRINTS SCHOOLHOUSE (AMK) PTE. LTD. SINGAPORE 569880 |569880   |32682.0063954461 |39989.3313855752 |1.37792345221534 |103.875389838376 |LUCAS CHILDREN ACADEMY PTE. LTD. |7030     |ANG MO KIO AVENUE 5 |LUCAS CHILDREN ACADEMY PTE. LTD. |7030 ANG MO KIO AVENUE 5 LUCAS CHILDREN ACADEMY PTE. LTD. SINGAPORE 569880 |569880   |32682.0063954461 |39989.3313855752 |1.37792345221534 |103.875389838376 |NORTHSTAR @ AMK |7030     |ANG MO KIO AVENUE 5 |NORTHSTAR @ AMK |7030 ANG MO KIO AVENUE 5 NORTHSTAR @ AMK SINGAPORE 569880 |569880   |32700.5844903681 |39939.0796920396 |1.37746899102804 |103.875556768146 |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |POINT (32682.01 39989.33) |\n|202527692C |ACRA               |ASH + EVE PTE. LTD.        |Local Company                    |na                                |Private Company Limited by Shares        |na                           |Live Company              |2025-06-26 |2025-06-26     |LOCAL        |160   |ROBINSON ROAD       |14       |04      |SINGAPORE BUSINESS FEDERATION CENTER |068914      |na                  |na                  |2026-12-31       |na                 |             96012|na                       |na                              | 2025|         6|Jun        |SINGAPORE BUSINESS FEDERATION CENTER (SBF CENTER) |160    |ROBINSON ROAD       |SINGAPORE BUSINESS FEDERATION CENTER (SBF CENTER) |160 ROBINSON ROAD SINGAPORE BUSINESS FEDERATION CENTER (SBF CENTER) SINGAPORE 068914 |1.27812790985944 |103.847854628243 |068914              |NA                                   |NA       |NA                  |NA                                   |NA                                                                             |NA       |NA               |NA               |NA               |NA               |NA                                  |NA       |NA                  |NA                                  |NA                                                                            |NA       |NA               |NA               |NA               |NA               |NA                                            |NA       |NA                  |NA                                            |NA                                                                                      |NA       |NA               |NA               |NA               |NA               |NA                               |NA       |NA                  |NA                               |NA                                                                         |NA       |NA               |NA               |NA               |NA               |NA              |NA       |NA                  |NA              |NA                                                        |NA       |NA               |NA               |NA               |NA               |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |POINT (29617.75 28954.42) |\n|53489069E  |ACRA               |AQUAFRESH EXPRESS          |Sole Proprietorship/ Partnership |Sole-Proprietor                   |na                                       |na                           |Ceased Registration       |2024-07-24 |2024-07-24     |LOCAL        |842G  |TAMPINES STREET 82  |14       |86      |TAMPINES ARCADIA                     |527842      |na                  |na                  |na               |na                 |             96012|na                       |na                              | 2024|         7|Jul        |TAMPINES ARCADIA                                  |842G   |TAMPINES STREET 82  |TAMPINES ARCADIA                                  |842G TAMPINES STREET 82 TAMPINES ARCADIA SINGAPORE 527842                            |1.35207674741611 |103.937111715862 |527842              |NA                                   |NA       |NA                  |NA                                   |NA                                                                             |NA       |NA               |NA               |NA               |NA               |NA                                  |NA       |NA                  |NA                                  |NA                                                                            |NA       |NA               |NA               |NA               |NA               |NA                                            |NA       |NA                  |NA                                            |NA                                                                                      |NA       |NA               |NA               |NA               |NA               |NA                               |NA       |NA                  |NA                               |NA                                                                         |NA       |NA               |NA               |NA               |NA               |NA              |NA       |NA                  |NA              |NA                                                        |NA       |NA               |NA               |NA               |NA               |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |POINT (39551.01 37131.54) |\n|53503312E  |ACRA               |A & B LAUNDRY              |Sole Proprietorship/ Partnership |Partnership                       |na                                       |na                           |Live                      |2025-04-30 |2025-04-30     |LOCAL        |5     |KIM CHUAN TERRACE   |na       |na      |na                                   |537028      |na                  |na                  |na               |na                 |             96012|na                       |na                              | 2025|         4|Apr        |5 KIM CHUAN TERRACE SINGAPORE 537028              |5      |KIM CHUAN TERRACE   |NIL                                               |5 KIM CHUAN TERRACE SINGAPORE 537028                                                 |1.33932059888709 |103.890529559767 |537028              |NA                                   |NA       |NA                  |NA                                   |NA                                                                             |NA       |NA               |NA               |NA               |NA               |NA                                  |NA       |NA                  |NA                                  |NA                                                                            |NA       |NA               |NA               |NA               |NA               |NA                                            |NA       |NA                  |NA                                            |NA                                                                                      |NA       |NA               |NA               |NA               |NA               |NA                               |NA       |NA                  |NA                               |NA                                                                         |NA       |NA               |NA               |NA               |NA               |NA              |NA       |NA                  |NA              |NA                                                        |NA       |NA               |NA               |NA               |NA               |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |NA          |NA       |NA          |NA         |NA        |NA       |NA  |NA  |NA         |NA          |POINT (34366.97 35720.86) |\n\n\n:::\n:::\n\n\n\n\n### 2.6 Import geospatial data into R\n\n*The Master Plan 2019 Boundary (No Sea) (KML)* was downloaded from data.gov.sg that consists of the geographical boundary of Singapore at the planning subzone level. The data is based on URA Master Plan 2019. We will use this to plot the boundaries of the subzones.\n\n::: panel-tabset\n## Import data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- st_read(\"data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaKML.kml\") %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `URA_MP19_SUBZONE_NO_SEA_PL' from data source \n  `/Users/cathyc/Documents/cathyschu/ISSS626GEO/Take-home_Ex/Take-home_Ex01/data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaKML.kml' \n  using driver `KML'\nSimple feature collection with 332 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY, XYZ\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n\n## Tidy data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_kml_field <- function(html_text, field_name) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_)\n  \n  page <- read_html(html_text)\n  rows <- page %>% html_elements(\"tr\")\n  \n  value <- rows %>%\n    keep(~ html_text2(html_element(.x, \"th\")) == field_name) %>%\n    html_element(\"td\") %>%\n    html_text2()\n  \n  if (length(value) == 0) NA_character_ else value\n}\n\nmpsz <- mpsz %>%\n  mutate(\n    REGION_N = map_chr(Description, extract_kml_field, \"REGION_N\"),\n    PLN_AREA_N = map_chr(Description, extract_kml_field, \"PLN_AREA_N\"),\n    SUBZONE_N = map_chr(Description, extract_kml_field, \"SUBZONE_N\"),\n    SUBZONE_C = map_chr(Description, extract_kml_field, \"SUBZONE_C\")\n  ) %>%\n  dplyr::select(-Name, -Description) %>%\n  relocate(geometry, .after = last_col())\n\nmpsz_cl <- mpsz %>%\n  filter(SUBZONE_N != \"SOUTHERN GROUP\",\n         PLN_AREA_N != \"WESTERN ISLANDS\",\n         PLN_AREA_N != \"NORTH-EASTERN ISLANDS\")\n```\n:::\n\n\n\n\n## Check data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_cl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 327 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 21448.47 xmax: 55941.94 ymax: 50256.33\nProjected CRS: SVY21 / Singapore TM\nFirst 10 features:\n         REGION_N    PLN_AREA_N           SUBZONE_N SUBZONE_C\n1  CENTRAL REGION   BUKIT MERAH          DEPOT ROAD    BMSZ12\n2  CENTRAL REGION   BUKIT MERAH         BUKIT MERAH    BMSZ02\n3  CENTRAL REGION        OUTRAM           CHINATOWN    OTSZ03\n4  CENTRAL REGION DOWNTOWN CORE             PHILLIP    DTSZ04\n5  CENTRAL REGION DOWNTOWN CORE       RAFFLES PLACE    DTSZ05\n6  CENTRAL REGION        OUTRAM        CHINA SQUARE    OTSZ04\n7  CENTRAL REGION   BUKIT MERAH         TIONG BAHRU    BMSZ10\n8  CENTRAL REGION DOWNTOWN CORE    BAYFRONT SUBZONE    DTSZ12\n9  CENTRAL REGION   BUKIT MERAH TIONG BAHRU STATION    BMSZ04\n10 CENTRAL REGION DOWNTOWN CORE       CLIFFORD PIER    DTSZ06\n                         geometry\n1  MULTIPOLYGON (((25910.34 29...\n2  MULTIPOLYGON (((26750.09 29...\n3  MULTIPOLYGON (((29161.2 297...\n4  MULTIPOLYGON (((29814.11 29...\n5  MULTIPOLYGON (((30137.77 29...\n6  MULTIPOLYGON (((29699.44 29...\n7  MULTIPOLYGON (((27748.04 29...\n8  MULTIPOLYGON (((30844.87 29...\n9  MULTIPOLYGON (((27444.04 29...\n10 MULTIPOLYGON (((30436.73 29...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mpsz_cl, \"data/rds/mpsz_cl.rds\")\n```\n:::\n\n\n\n:::\n\n\n### 2.7 Prepare population data\n\n:::panel-tabset\n## Import data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopdata <- read_csv(\"data/aspatial/respopagesextod2024.csv\")\nkable(head(popdata))\n```\n\n::: {.cell-output-display}\n\n\n|PA         |SZ                     |AG     |Sex   |TOD                                     | Pop| Time|\n|:----------|:----------------------|:------|:-----|:---------------------------------------|---:|----:|\n|Ang Mo Kio |Ang Mo Kio Town Centre |0_to_4 |Males |HDB 1- and 2-Room Flats                 |   0| 2024|\n|Ang Mo Kio |Ang Mo Kio Town Centre |0_to_4 |Males |HDB 3-Room Flats                        |   0| 2024|\n|Ang Mo Kio |Ang Mo Kio Town Centre |0_to_4 |Males |HDB 4-Room Flats                        |  10| 2024|\n|Ang Mo Kio |Ang Mo Kio Town Centre |0_to_4 |Males |HDB 5-Room and Executive Flats          |  20| 2024|\n|Ang Mo Kio |Ang Mo Kio Town Centre |0_to_4 |Males |HUDC Flats (excluding those privatised) |   0| 2024|\n|Ang Mo Kio |Ang Mo Kio Town Centre |0_to_4 |Males |Condominiums and Other Apartments       |  40| 2024|\n\n\n:::\n:::\n\n\n\n\n## Data wrangling\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopdata2024 <- popdata %>%\n  group_by(PA, SZ) %>%\n  summarise(TOTAL_POP = sum(`Pop`)) %>%\n  ungroup() \n\nkable(head(popdata2024))\n```\n\n::: {.cell-output-display}\n\n\n|PA         |SZ                     | TOTAL_POP|\n|:----------|:----------------------|---------:|\n|Ang Mo Kio |Ang Mo Kio Town Centre |      4910|\n|Ang Mo Kio |Cheng San              |     27040|\n|Ang Mo Kio |Chong Boon             |     25310|\n|Ang Mo Kio |Kebun Bahru            |     22090|\n|Ang Mo Kio |Sembawang Hills        |      6920|\n|Ang Mo Kio |Shangri-La             |     17570|\n\n\n:::\n:::\n\n\n\n\n\n## Join population and geospatial data\n\nUse left_join to join the population data and geospatial data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopdata2024 <- popdata2024 %>%\n  mutate_at(.vars = vars(PA, SZ),\n            .funs = list(toupper)) %>%\n  filter(`TOTAL_POP` > 0)\nmpsz_pop2024 <- left_join(mpsz_cl, popdata2024,\n                          by = c(\"SUBZONE_N\" = \"SZ\"))\n```\n:::\n\n\n\n\nThen write it into a rds file.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mpsz_pop2024, \"data/rds/mpsz_pop2024.rds\")\n```\n:::\n\n\n\n\n\nWe will call it from rds file to save computation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_pop2024 <- read_rds(\"data/rds/mpsz_pop2024.rds\")\n```\n:::\n\n\n\n\n\n:::\n\n## 3 First-order Analysis\n\n<summary for first-order analysis>\n\n\n::: panel-tabset\n## Laundry Services\n### Mapping geospatial data sets\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nplot(st_geometry(mpsz_cl), border = \"grey70\")\nplot(st_geometry(biz_9601_sf), add = TRUE, col = \"#FF9800\", pch = 16, cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n### Mapping with population\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\ntmap_mode(\"plot\")\n\ntm_shape(mpsz_pop2024) +\n  tm_polygons(col = \"TOTAL_POP\", \n          border.col = \"#7077A1\", lwd = 0.3) +\ntm_shape(biz_9601_sf) +\n  tm_dots(col = \"#FF9800\", size = 0.3, alpha = 0.9) +\ntm_layout(bg.color =  \"#EEEEEE\",\n          outer.bg.color = NA,\n          frame = FALSE,\n          legend.bg.color = \"transparent\",      \n          legend.frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n::::: notegoals\n::: noterkgoals-header\n**Insight**\n:::\nNew laundry businesses appeared concentrated in both residential and commercial areas. We see in the figure above that \n::: notegoals-container\n\n:::\n:::::\n\n\n## Beauty Services\n### Mapping geospatial data sets\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nplot(st_geometry(mpsz_cl), border = \"grey70\")\nplot(st_geometry(biz_9602_sf), add = TRUE, col = \"#BA487F\", pch = 16, cex = 0.5)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n\n### Mapping with population\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\ntmap_mode(\"plot\")\n\ntm_shape(mpsz_pop2024) +\n  tm_polygons(col = \"TOTAL_POP\", \n          border.col = \"#7077A1\", lwd = 0.3) +\ntm_shape(biz_9602_sf) +\n  tm_dots(col = \"#BA487F\", size = 0.2, alpha = 0.9) +\ntm_layout(bg.color =  \"#EEEEEE\",\n          outer.bg.color = NA,\n          frame = FALSE,\n          legend.bg.color = \"transparent\",      \n          legend.frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n::::: notegoals\n::: noterkgoals-header\n**Insight**\n:::\n\n::: notegoals-container\n\n:::\n:::::\n\n## Dental Services\n### Mapping geospatial data sets\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nplot(st_geometry(mpsz_cl), border = \"grey70\")\nplot(st_geometry(biz_86204_sf), add = TRUE, col = \"#18978F\", pch = 16, cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n\n### Mapping with population\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\ntmap_mode(\"plot\")\n\ntm_shape(mpsz_pop2024) +\n  tm_polygons(col = \"TOTAL_POP\", \n          border.col = \"#7077A1\", lwd = 0.3) +\ntm_shape(biz_86204_sf) +\n  tm_dots(col = \"#18978F\", size = 0.3, alpha = 0.9) +\ntm_layout(bg.color =  \"#EEEEEE\",\n          outer.bg.color = NA,\n          frame = FALSE,\n          legend.bg.color = \"transparent\",      \n          legend.frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n\n::::: notegoals\n::: noterkgoals-header\n**Insight**\n:::\n\n::: notegoals-container\n\n:::\n:::::\n\n:::\n\n### 3.1 Spatial KDE\n\n<summary of spatial KDE>\n\n#### 3.1.1 Geospatial data wrangling\n\nIn this section, we will convert the sf objects to spatstat ppp and owin object.\n\n::: panel-tabset\n## Laundry Services\n\n**Convert sf data frames to ppp class**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601_ppp <- as.ppp(biz_9601_sf)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(biz_9601_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  150 points\nAverage intensity 2.250502e-07 points per square unit\n\nCoordinates are given to 11 decimal places\n\nMark variables: uen, issuance_agency_id, entity_name, entity_type_description, \nbusiness_constitution_description, company_type_description, \npaf_constitution_description, entity_status_description, date, uen_issue_date, \naddress_type, block, street_name, level_no, unit_no, building_name, \npostal_code, other_address_line1, other_address_line2, account_due_date, \nannual_return_date, primary_ssic_code, primary_ssic_description, \nprimary_user_described_activity, YEAR, MONTH_NUM, MONTH_ABBR, SEARCHVAL, \nBLK_NO, ROAD_NAME, BUILDING, ADDRESS, LATITUDE, LONGITUDE, input_postcode_9601, \nSEARCHVAL.1, BLK_NO.1, ROAD_NAME.1, BUILDING.1, ADDRESS.1, POSTAL.1, X.1, Y.1, \nLATITUDE.1, LONGITUDE.1, SEARCHVAL.2, BLK_NO.2, ROAD_NAME.2, BUILDING.2, \nADDRESS.2, POSTAL.2, X.2, Y.2, LATITUDE.2, LONGITUDE.2, SEARCHVAL.3, BLK_NO.3, \nROAD_NAME.3, BUILDING.3, ADDRESS.3, POSTAL.3, X.3, Y.3, LATITUDE.3, \nLONGITUDE.3, SEARCHVAL.4, BLK_NO.4, ROAD_NAME.4, BUILDING.4, ADDRESS.4, \nPOSTAL.4, X.4, Y.4, LATITUDE.4, LONGITUDE.4, SEARCHVAL.5, BLK_NO.5, \nROAD_NAME.5, BUILDING.5, ADDRESS.5, POSTAL.5, X.5, Y.5, LATITUDE.5, \nLONGITUDE.5, SEARCHVAL.6, BLK_NO.6, ROAD_NAME.6, BUILDING.6, ADDRESS.6, \nPOSTAL.6, X.6, Y.6, LATITUDE.6, LONGITUDE.6, SEARCHVAL.7, BLK_NO.7, \nROAD_NAME.7, BUILDING.7, ADDRESS.7, POSTAL.7, X.7, Y.7, LATITUDE.7, \nLONGITUDE.7, SEARCHVAL.8, BLK_NO.8, ROAD_NAME.8, BUILDING.8, ADDRESS.8, \nPOSTAL.8, X.8, Y.8, LATITUDE.8, LONGITUDE.8, SEARCHVAL.9, BLK_NO.9, \nROAD_NAME.9, BUILDING.9, ADDRESS.9, POSTAL.9, X.9, Y.9, LATITUDE.9, LONGITUDE.9\nSummary:\n     uen            issuance_agency_id entity_name       \n Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n                                                         \n entity_type_description business_constitution_description\n Length:150              Length:150                       \n Class :character        Class :character                 \n Mode  :character        Mode  :character                 \n                                                          \n                                                          \n                                                          \n                                                          \n company_type_description paf_constitution_description\n Length:150               Length:150                  \n Class :character         Class :character            \n Mode  :character         Mode  :character            \n                                                      \n                                                      \n                                                      \n                                                      \n entity_status_description      date            uen_issue_date      \n Length:150                Min.   :2024-01-03   Min.   :2024-01-03  \n Class :character          1st Qu.:2024-05-14   1st Qu.:2024-05-14  \n Mode  :character          Median :2024-09-17   Median :2024-09-17  \n                           Mean   :2024-09-26   Mean   :2024-09-27  \n                           3rd Qu.:2025-02-18   3rd Qu.:2025-02-18  \n                           Max.   :2025-06-26   Max.   :2025-06-26  \n                                                                    \n address_type          block           street_name          level_no        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   unit_no          building_name      postal_code        other_address_line1\n Length:150         Length:150         Length:150         Length:150         \n Class :character   Class :character   Class :character   Class :character   \n Mode  :character   Mode  :character   Mode  :character   Mode  :character   \n                                                                             \n                                                                             \n                                                                             \n                                                                             \n other_address_line2 account_due_date   annual_return_date primary_ssic_code\n Length:150          Length:150         Length:150         Min.   :96011    \n Class :character    Class :character   Class :character   1st Qu.:96011    \n Mode  :character    Mode  :character   Mode  :character   Median :96012    \n                                                           Mean   :96012    \n                                                           3rd Qu.:96012    \n                                                           Max.   :96012    \n                                                                            \n primary_ssic_description primary_user_described_activity      YEAR     \n Length:150               Length:150                      Min.   :2024  \n Class :character         Class :character                1st Qu.:2024  \n Mode  :character         Mode  :character                Median :2024  \n                                                          Mean   :2024  \n                                                          3rd Qu.:2025  \n                                                          Max.   :2025  \n                                                                        \n   MONTH_NUM        MONTH_ABBR  SEARCHVAL            BLK_NO         \n Min.   : 1.000   Jan    :23   Length:150         Length:150        \n 1st Qu.: 3.000   Mar    :21   Class :character   Class :character  \n Median : 5.000   May    :16   Mode  :character   Mode  :character  \n Mean   : 5.073   Apr    :15                                        \n 3rd Qu.: 7.000   Jun    :15                                        \n Max.   :12.000   Feb    :13                                        \n                  (Other):47                                        \n  ROAD_NAME           BUILDING           ADDRESS            LATITUDE        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  LONGITUDE         input_postcode_9601 SEARCHVAL.1          BLK_NO.1        \n Length:150         Length:150          Length:150         Length:150        \n Class :character   Class :character    Class :character   Class :character  \n Mode  :character   Mode  :character    Mode  :character   Mode  :character  \n                                                                             \n                                                                             \n                                                                             \n                                                                             \n ROAD_NAME.1         BUILDING.1         ADDRESS.1           POSTAL.1        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     X.1                Y.1             LATITUDE.1        LONGITUDE.1       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n SEARCHVAL.2          BLK_NO.2         ROAD_NAME.2         BUILDING.2       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ADDRESS.2           POSTAL.2             X.2                Y.2           \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  LATITUDE.2        LONGITUDE.2        SEARCHVAL.3          BLK_NO.3        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n ROAD_NAME.3         BUILDING.3         ADDRESS.3           POSTAL.3        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     X.3                Y.3             LATITUDE.3        LONGITUDE.3       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n SEARCHVAL.4          BLK_NO.4         ROAD_NAME.4         BUILDING.4       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ADDRESS.4           POSTAL.4             X.4                Y.4           \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  LATITUDE.4        LONGITUDE.4        SEARCHVAL.5          BLK_NO.5        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n ROAD_NAME.5         BUILDING.5         ADDRESS.5           POSTAL.5        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     X.5                Y.5             LATITUDE.5        LONGITUDE.5       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n SEARCHVAL.6          BLK_NO.6         ROAD_NAME.6         BUILDING.6       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ADDRESS.6           POSTAL.6             X.6                Y.6           \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  LATITUDE.6        LONGITUDE.6        SEARCHVAL.7          BLK_NO.7        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n ROAD_NAME.7         BUILDING.7         ADDRESS.7           POSTAL.7        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     X.7                Y.7             LATITUDE.7        LONGITUDE.7       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n SEARCHVAL.8          BLK_NO.8         ROAD_NAME.8         BUILDING.8       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ADDRESS.8           POSTAL.8             X.8                Y.8           \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  LATITUDE.8        LONGITUDE.8        SEARCHVAL.9          BLK_NO.9        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n ROAD_NAME.9         BUILDING.9         ADDRESS.9           POSTAL.9        \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     X.9                Y.9             LATITUDE.9        LONGITUDE.9       \n Length:150         Length:150         Length:150         Length:150        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n\nWindow: rectangle = [9649.27, 43229.92] x [28689.89, 48538.17] units\n                    (33580 x 19850 units)\nWindow area = 666518000 square units\n```\n\n\n:::\n:::\n\n\n\n\n**Create Owin object**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg_owin <- as.owin(mpsz_cl)\n```\n:::\n\n\n\n\n**Combine point events object and owin object**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601_ppp = biz_9601_ppp[sg_owin]\nbiz_9601_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 150 points\nMark variables: \n   uen issuance_agency_id entity_name entity_type_description \nbusiness_constitution_description company_type_description \npaf_constitution_description entity_status_description date uen_issue_date \naddress_type block street_name level_no unit_no building_name postal_code \nother_address_line1 other_address_line2 account_due_date annual_return_date \nprimary_ssic_code primary_ssic_description primary_user_described_activity YEAR \nMONTH_NUM MONTH_ABBR SEARCHVAL BLK_NO ROAD_NAME BUILDING ADDRESS LATITUDE \nLONGITUDE input_postcode_9601 SEARCHVAL.1 BLK_NO.1 ROAD_NAME.1 BUILDING.1 \nADDRESS.1 POSTAL.1 X.1 Y.1 LATITUDE.1 LONGITUDE.1 SEARCHVAL.2 BLK_NO.2 \nROAD_NAME.2 BUILDING.2 ADDRESS.2 POSTAL.2 X.2 Y.2 LATITUDE.2 LONGITUDE.2 \nSEARCHVAL.3 BLK_NO.3 ROAD_NAME.3 BUILDING.3 ADDRESS.3 POSTAL.3 X.3 Y.3 \nLATITUDE.3 LONGITUDE.3 SEARCHVAL.4 BLK_NO.4 ROAD_NAME.4 BUILDING.4 ADDRESS.4 \nPOSTAL.4 X.4 Y.4 LATITUDE.4 LONGITUDE.4 SEARCHVAL.5 BLK_NO.5 ROAD_NAME.5 \nBUILDING.5 ADDRESS.5 POSTAL.5 X.5 Y.5 LATITUDE.5 LONGITUDE.5 SEARCHVAL.6 \nBLK_NO.6 ROAD_NAME.6 BUILDING.6 ADDRESS.6 POSTAL.6 X.6 Y.6 LATITUDE.6 \nLONGITUDE.6 SEARCHVAL.7 BLK_NO.7 ROAD_NAME.7 BUILDING.7 ADDRESS.7 POSTAL.7 X.7 \nY.7 LATITUDE.7 LONGITUDE.7 SEARCHVAL.8 BLK_NO.8 ROAD_NAME.8 BUILDING.8 \nADDRESS.8 POSTAL.8 X.8 Y.8 LATITUDE.8 LONGITUDE.8 SEARCHVAL.9 BLK_NO.9 \nROAD_NAME.9 BUILDING.9 ADDRESS.9 POSTAL.9 X.9 Y.9 LATITUDE.9 LONGITUDE.9\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n\n\n## Beauty Services\n\n**Convert sf data frames to ppp class**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602_ppp <- as.ppp(biz_9602_sf)\n```\n:::\n\n\n\n\n**Combine point events object and owin object**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602_ppp = biz_9602_ppp[sg_owin]\nbiz_9602_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 1762 points\nMark variables: \n   uen issuance_agency_id entity_name entity_type_description \nbusiness_constitution_description company_type_description \npaf_constitution_description entity_status_description date uen_issue_date \naddress_type block street_name level_no unit_no building_name postal_code \nother_address_line1 other_address_line2 account_due_date annual_return_date \nprimary_ssic_code primary_ssic_description primary_user_described_activity YEAR \nMONTH_NUM MONTH_ABBR SEARCHVAL BLK_NO ROAD_NAME BUILDING ADDRESS LATITUDE \nLONGITUDE SEARCHVAL.1 BLK_NO.1 ROAD_NAME.1 BUILDING.1 ADDRESS.1 POSTAL.1 X.1 \nY.1 LATITUDE.1 LONGITUDE.1 SEARCHVAL.2 BLK_NO.2 ROAD_NAME.2 BUILDING.2 \nADDRESS.2 POSTAL.2 X.2 Y.2 LATITUDE.2 LONGITUDE.2 SEARCHVAL.3 BLK_NO.3 \nROAD_NAME.3 BUILDING.3 ADDRESS.3 POSTAL.3 X.3 Y.3 LATITUDE.3 LONGITUDE.3 \nSEARCHVAL.4 BLK_NO.4 ROAD_NAME.4 BUILDING.4 ADDRESS.4 POSTAL.4 X.4 Y.4 \nLATITUDE.4 LONGITUDE.4 SEARCHVAL.5 BLK_NO.5 ROAD_NAME.5 BUILDING.5 ADDRESS.5 \nPOSTAL.5 X.5 Y.5 LATITUDE.5 LONGITUDE.5 input_postcode_9602 SEARCHVAL.6 \nBLK_NO.6 ROAD_NAME.6 BUILDING.6 ADDRESS.6 POSTAL.6 X.6 Y.6 LATITUDE.6 \nLONGITUDE.6 SEARCHVAL.7 BLK_NO.7 ROAD_NAME.7 BUILDING.7 ADDRESS.7 POSTAL.7 X.7 \nY.7 LATITUDE.7 LONGITUDE.7 SEARCHVAL.8 BLK_NO.8 ROAD_NAME.8 BUILDING.8 \nADDRESS.8 POSTAL.8 X.8 Y.8 LATITUDE.8 LONGITUDE.8 SEARCHVAL.9 BLK_NO.9 \nROAD_NAME.9 BUILDING.9 ADDRESS.9 POSTAL.9 X.9 Y.9 LATITUDE.9 LONGITUDE.9\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n\n\n## Dental Services\n\n**Convert sf data frames to ppp class**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204_ppp <- as.ppp(biz_86204_sf)\n```\n:::\n\n\n\n\n**Combine point events object and owin object**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204_ppp = biz_86204_ppp[sg_owin]\nbiz_86204_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 81 points\nMark variables: \n   uen issuance_agency_id entity_name entity_type_description \nbusiness_constitution_description company_type_description \npaf_constitution_description entity_status_description date uen_issue_date \naddress_type block street_name level_no unit_no building_name postal_code \nother_address_line1 other_address_line2 account_due_date annual_return_date \nprimary_ssic_code primary_ssic_description primary_user_described_activity YEAR \nMONTH_NUM MONTH_ABBR SEARCHVAL BLK_NO ROAD_NAME BUILDING ADDRESS LATITUDE \nLONGITUDE input_postcode_86204 SEARCHVAL.1 BLK_NO.1 ROAD_NAME.1 BUILDING.1 \nADDRESS.1 POSTAL.1 X.1 Y.1 LATITUDE.1 LONGITUDE.1 SEARCHVAL.2 BLK_NO.2 \nROAD_NAME.2 BUILDING.2 ADDRESS.2 POSTAL.2 X.2 Y.2 LATITUDE.2 LONGITUDE.2 \nSEARCHVAL.3 BLK_NO.3 ROAD_NAME.3 BUILDING.3 ADDRESS.3 POSTAL.3 X.3 Y.3 \nLATITUDE.3 LONGITUDE.3 SEARCHVAL.4 BLK_NO.4 ROAD_NAME.4 BUILDING.4 ADDRESS.4 \nPOSTAL.4 X.4 Y.4 LATITUDE.4 LONGITUDE.4 SEARCHVAL.5 BLK_NO.5 ROAD_NAME.5 \nBUILDING.5 ADDRESS.5 POSTAL.5 X.5 Y.5 LATITUDE.5 LONGITUDE.5\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n\n:::\n\n#### 3.1.2 Clark-Evans test\n\nIn this section, we will perform Clark-Evans tests for the 3 business entities separately, to quantify whether a point pattern is clustered, random, or uniformly spaced. The result will help us understand the underlying spatial patterns of each business type. This will inform our interpretation of the subsequent KDE analysis.\n\n::: panel-tabset\n## Laundry Services\n\nThe test hypotheses are: Ho = The distribution of laundry services are randomly distributed. H1 = The distribution of laundry services are not randomly distributed. The 95% confident interval will be used.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(biz_9601_ppp,\n                correction=\"none\",\n                clipregion=\"sg_owin\",\n                alternative=c(\"clustered\"),\n                method=\"MonteCarlo\",\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 999 simulations of CSR with fixed n\n\ndata:  biz_9601_ppp\nR = 0.59189, p-value = 0.001\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n\nLaundry service R = 0.59189 shows there are some clustering in residential areas. It is more dispersed to serve neighbourhood needs, but it is not random.\n\n## Beauty Services\n\nThe test hypotheses are: Ho = The distribution of beauty services are randomly distributed. H1 = The distribution of beauty services are not randomly distributed. The 95% confident interval will be used.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(biz_9602_ppp,\n                correction=\"none\",\n                clipregion=\"sg_owin\",\n                alternative=c(\"clustered\"),\n                method=\"MonteCarlo\",\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 999 simulations of CSR with fixed n\n\ndata:  biz_9602_ppp\nR = 0.35898, p-value = 0.001\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n\nBeauty services (R = 0.36) indicates that they are most clustered.\n\n## Dental Services\n\nThe test hypotheses are:\n\nHo = The distribution of dental services are randomly distributed.\n\nH1 = The distribution of dental services are not randomly distributed. The 95% confident interval will be used.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(biz_86204_ppp,\n                correction=\"none\",\n                clipregion=\"sg_owin\",\n                alternative=c(\"clustered\"),\n                method=\"MonteCarlo\",\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 999 simulations of CSR with fixed n\n\ndata:  biz_86204_ppp\nR = 0.49043, p-value = 0.001\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n\nDental service R = 0.49043 shows moderate clustering. This is possibily due to medical professional buildigs or proximity to hospitals.\n:::\n\n#### 3.1.3 Compute KDE with adaptive bandwidth\n\nWe will compute Kernel Density Estimation (KDE) to visualise and analyse first-order spatial point patterns. We use adaptive bandwidth because all 3 business types show significant clustering with varying intensities, and adaptive approach handles multi-scale density variations beter than fixed bandwidth by using finer resolution in high-density areas and broader smoothing in sparse regions.\n\n::: panel-tabset\n## Laundry Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nbiz_9601_ppp_km <- rescale.ppp(biz_9601_ppp, 1000, \"km\")\nkde_biz_9601_ab <- adaptive.density(\n  biz_9601_ppp_km, method = \"kernel\"\n)\nplot(kde_biz_9601_ab,\n     col = terrain.colors(256)) \n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n\n\n## Beauty Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nbiz_9602_ppp_km <- rescale.ppp(biz_9602_ppp, 1000, \"km\")\nkde_biz_9602_ab <- adaptive.density(\n  biz_9602_ppp_km, method = \"kernel\"\n)\nplot(kde_biz_9602_ab,\n     col = terrain.colors(256))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n\n\n## Dental Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nbiz_86204_ppp_km <- rescale.ppp(biz_86204_ppp, 1000, \"km\")\nkde_biz_86204_ab <- adaptive.density(\n  biz_86204_ppp_km, method = \"kernel\"\n)\nplot(kde_biz_86204_ab,\n     col = terrain.colors(256))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n### 3.2 Spatio-Temporal KDE\n\nJaundry, Beauty, and Dental business types have 150, 1762 and 81 points respectively during Jan 2024 - June 2025. In this study, we will slice the data compute quarterly spatio-temporal KDE for analysis to see seasonal patterns.\n\n#### 3.2.1 Visualise business entity points by month/quarter\n\n::: panel-tabset\n## Laundry Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601_quarter <- biz_9601_sf %>%\n  mutate(\n    quarter = case_when(\n      MONTH_NUM %in% c(1, 2, 3) ~ \"Q1\",\n      MONTH_NUM %in% c(4, 5, 6) ~ \"Q2\",\n      MONTH_NUM %in% c(7, 8, 9) ~ \"Q3\",\n      MONTH_NUM %in% c(10, 11, 12) ~ \"Q4\"\n    ),\n    year_quarter = paste(YEAR, quarter, sep = \"-\")\n  )\n\ntmap_options(bg.color = \"#EEEEEE\")\ntm_shape(mpsz_cl) + \n  tm_polygons(fill = \"#FFF2F2\", col = \"grey80\") +\ntm_shape(biz_9601_quarter) +\n  tm_dots(fill = \"#476EAE\", size = 0.4) +\n  tm_facets(by = \"year_quarter\", free.coords = FALSE, drop.units = TRUE,\n            ncol = 2) +\ntm_layout(\n    main.title = \"Laundry Services - Quarterly Density\",\n    bg.color = \"#EED3D9\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-47-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Beauty Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602_my <- biz_9602_sf %>%\n  mutate(\n    date = as.Date(paste(YEAR, MONTH_NUM, \"01\", sep = \"-\")),\n    month_year = format(date, \"%Y-%m\"),\n    month_year_label = format(date, \"%b %Y\")\n  )\n\ntmap_options(bg.color = \"#EEEEEE\")\ntm_shape(mpsz_cl) + \n  tm_polygons(fill = \"#FFF2F2\", col = \"grey80\") +\n  tm_shape(biz_9602_my) +\n  tm_dots(fill = \"#BA487F\", size = 0.2) +\n  tm_facets(by = \"month_year\", free.coords = FALSE, drop.units = TRUE,\n            ncol = 2) +\ntm_layout(\n    main.title = \"Beauty Services - Monthly Density\",\n    bg.color = \"#CADABF\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-48-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Dental Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204_quarter <- biz_86204_sf %>%\n  mutate(\n    quarter = case_when(\n      MONTH_NUM %in% c(1, 2, 3) ~ \"Q1\",\n      MONTH_NUM %in% c(4, 5, 6) ~ \"Q2\",\n      MONTH_NUM %in% c(7, 8, 9) ~ \"Q3\",\n      MONTH_NUM %in% c(10, 11, 12) ~ \"Q4\"\n    ),\n    year_quarter = paste(YEAR, quarter, sep = \"-\")\n  )\n\ntmap_options(bg.color = \"#EEEEEE\")\ntm_shape(mpsz_cl) + \n  tm_polygons(fill = \"#FFF2F2\", col = \"grey80\") +\n  tm_shape(biz_86204_quarter) +\n  tm_dots(fill = \"#EF7722\", size = 0.4) +\n  tm_facets(by = \"year_quarter\", free.coords = FALSE, drop.units = TRUE,\n            ncol = 2) +\ntm_layout(\n    main.title = \"Dental Services - Quarterly Density\",\n    bg.color = \"#B5C0D0\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-49-1.png){width=1152}\n:::\n:::\n\n\n\n:::\n\n#### 3.2.2 Compute Spatio-Temporal STKDE by month/quarter\n\n::: panel-tabset\n## Laundry Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract laundry data by quarter\nkde_biz_9601_quarter <- biz_9601_quarter %>%\n  dplyr::select(year_quarter)\n\n# create ppp\nbiz_9601_quarter_ppp <- as.ppp(kde_biz_9601_quarter)\n  \n\n# include owin object\nbiz_9601_quarter_owin <- biz_9601_quarter_ppp[sg_owin]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nplot(biz_9601_quarter_owin)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\n\n\n### Compute STKDE\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#convert year_quarter to numeric\nmarks(biz_9601_quarter_owin) <- case_when(\n  marks(biz_9601_quarter_owin) == \"2024-Q1\" ~ 1,\n  marks(biz_9601_quarter_owin) == \"2024-Q2\" ~ 2,\n  marks(biz_9601_quarter_owin) == \"2024-Q3\" ~ 3,\n  marks(biz_9601_quarter_owin) == \"2024-Q4\" ~ 4,\n  marks(biz_9601_quarter_owin) == \"2025-Q1\" ~ 5,\n  marks(biz_9601_quarter_owin) == \"2025-Q2\" ~ 6\n)\n\nst_kde_9601 <- spattemp.density(biz_9601_quarter_owin)\nsummary(st_kde_9601)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 2692.247 (spatial)\n  lambda = 0.0882 (temporal)\n\nNo. of observations\n  150 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [2667.538, 55941.94] x [21448.47, 50256.33]\n\nTemporal bound\n  [1, 6]\n\nEvaluation\n  128 x 128 x 6 trivariate lattice\n  Density range: [2.767051e-23, 1.279663e-08]\n```\n\n\n:::\n:::\n\n\n\n\n### Plot STKDE object\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(1,2,3,4,5,6)\npar(mfrow = c(2,3), bg = \"#EEEEEE\")\nfor(i in tims){\n  plot(st_kde_9601, i,\n       override.par = FALSE,\n       fix.range = TRUE, main = paste(\"Laundry Services KDE at Quarter\", i\n     ), col = terrain.colors(256))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-53-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Beauty Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract laundry data by quarter\nkde_biz_9602_month <- biz_9602_my %>%\n  dplyr::select(month_year)\n\n# create ppp\nbiz_9602_month_ppp <- as.ppp(kde_biz_9602_month)\n  \n\n# include owin object\nbiz_9602_month_owin <- biz_9602_month_ppp[sg_owin]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nplot(biz_9602_month_owin)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\n\n\n### Compute STKDE\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#convert year_quarter to numeric\nmarks(biz_9602_month_owin) <- case_when(\n  marks(biz_9602_month_owin) == \"2024-01\" ~ 1,\n  marks(biz_9602_month_owin) == \"2024-02\" ~ 2,\n  marks(biz_9602_month_owin) == \"2024-03\" ~ 3,\n  marks(biz_9602_month_owin) == \"2024-04\" ~ 4,\n  marks(biz_9602_month_owin) == \"2024-05\" ~ 5,\n  marks(biz_9602_month_owin) == \"2024-06\" ~ 6,\n  marks(biz_9602_month_owin) == \"2024-07\" ~ 7,\n  marks(biz_9602_month_owin) == \"2024-08\" ~ 8,\n  marks(biz_9602_month_owin) == \"2024-09\" ~ 9,\n  marks(biz_9602_month_owin) == \"2024-10\" ~ 10,\n  marks(biz_9602_month_owin) == \"2024-11\" ~ 11,\n  marks(biz_9602_month_owin) == \"2024-12\" ~ 12,  \n  marks(biz_9602_month_owin) == \"2025-01\" ~ 13,\n  marks(biz_9602_month_owin) == \"2025-02\" ~ 14,\n  marks(biz_9602_month_owin) == \"2025-03\" ~ 15,\n  marks(biz_9602_month_owin) == \"2025-04\" ~ 16,\n  marks(biz_9602_month_owin) == \"2025-05\" ~ 17,\n  marks(biz_9602_month_owin) == \"2025-06\" ~ 18\n  )\n\nst_kde_9602 <- spattemp.density(biz_9602_month_owin)\nsummary(st_kde_9602)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 1364.177 (spatial)\n  lambda = 0.0869 (temporal)\n\nNo. of observations\n  1762 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [2667.538, 55941.94] x [21448.47, 50256.33]\n\nTemporal bound\n  [1, 18]\n\nEvaluation\n  128 x 128 x 18 trivariate lattice\n  Density range: [6.715706e-53, 8.658812e-09]\n```\n\n\n:::\n:::\n\n\n\n\n### Plot STKDE object\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)\npar(mfrow = c(9,2), bg = \"#EEEEEE\")\nfor(i in tims){\n  plot(st_kde_9602, i,\n       override.par = FALSE,\n       fix.range = TRUE, main = paste(\"Beauty Services KDE at Month\", i),\n       col = terrain.colors(256))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-57-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Dental Services\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract laundry data by quarter\nkde_biz_86204_quarter <- biz_86204_quarter %>%\n  dplyr::select(year_quarter)\n\n# create ppp\nbiz_86204_quarter_ppp <- as.ppp(kde_biz_86204_quarter)\n  \n\n# include owin object\nbiz_86204_quarter_owin <- biz_86204_quarter_ppp[sg_owin]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nplot(biz_86204_quarter_owin)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\n\n### Compute STKDE\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#convert year_quarter to numeric\nmarks(biz_86204_quarter_owin) <- case_when(\n  marks(biz_86204_quarter_owin) == \"2024-Q1\" ~ 1,\n  marks(biz_86204_quarter_owin) == \"2024-Q2\" ~ 2,\n  marks(biz_86204_quarter_owin) == \"2024-Q3\" ~ 3,\n  marks(biz_86204_quarter_owin) == \"2024-Q4\" ~ 4,\n  marks(biz_86204_quarter_owin) == \"2025-Q1\" ~ 5,\n  marks(biz_86204_quarter_owin) == \"2025-Q2\" ~ 6\n)\n\nst_kde_86204 <- spattemp.density(biz_86204_quarter_owin)\nsummary(st_kde_86204)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 2190.678 (spatial)\n  lambda = 0.1279 (temporal)\n\nNo. of observations\n  81 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [2667.538, 55941.94] x [21448.47, 50256.33]\n\nTemporal bound\n  [1, 6]\n\nEvaluation\n  128 x 128 x 6 trivariate lattice\n  Density range: [9.274425e-36, 1.450286e-08]\n```\n\n\n:::\n:::\n\n\n\n\n### Plot STKDE object\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(1,2,3,4,5,6)\npar(mfrow = c(2,3), bg = \"#EEEEEE\")\nfor(i in tims){\n  plot(st_kde_86204, i,\n       override.par = FALSE,\n       fix.range = TRUE, main = paste(\"Dental Services KDE at Quarter\", i),\n       col = terrain.colors(256))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-61-1.png){width=1152}\n:::\n:::\n\n\n\n:::\n\n## 4 Second-order Analysis\n\n<overview>\n\n### 4.1 Spatial analysis\n\nIn this section, we will compute spatial point patterns\n\n::: panel-tabset\n## Laundry Services\n\nFor laundry services, we will use F-function to analyse spatial point process as this function is best for random locations to nearest business. Laundry services may be important to residents, be it dry cleaning or self-operated. We want to observe its distribution whether the placement is random or follows specific spatial strategy.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1222)\n```\n:::\n\n\n\n\n### F-function estimation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nF_9601 = Fest(biz_9601_ppp)\nplot(F_9601)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\n\n\n### Complete spatial randomness test\n\nWe use the hypothesis test below to confirm the spatial patterns above. Ho = The distribution of laundry services are randomly distributed. H1= The distribution of laundry services are not randomly distributed. The null hypothesis will be rejected is p-value is smaller than alpha value of 0.01.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_9601.csr <- envelope(biz_9601_ppp, Fest, correction = \"all\", nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n\n### Plot simulation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#EEEEEE\")\nplot(F_9601.csr)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\n\n\n<under envelope>\n\n## Beauty Services\n\nFor beauty services such as hair salons, manicure and pedicure, personal care services, we will use K-function to analyze clustering patterns by examining the expected number of neighboring businesses within given distances. The intention is to identify and quantify clustering at multiple spatial scales.\n\n### L-function estimate\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_9602 = Lest(biz_9602_ppp, correction = \"Ripley\")\nplot(L_9602, . -r ~ r, ylab = \"L(d)-r\", xlab = \"d(m)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n\n\n\n### Spatial randomness test\n\nThe hypothesis and test are as follows:\n\nHo = The distribution of Beauty services are randomly distributed.\n\nH1= The distribution of Beauty services are not randomly distributed.\n\nThe null hypothesis will be rejected if p-value is smaller than alpha value of 0.05.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_9602.csr <- envelope(biz_9602_ppp, Lest, nsim = 39, rank = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 39 simulations of CSR  ...\n1, 2, \n[1:30:15 remaining, estimate finish 2025-09-24 18:18:55]\n3, \n[1:26:24 remaining, estimate finish 2025-09-24 18:17:25]\n4, \n[1:23:24 remaining, estimate finish 2025-09-24 18:16:46]\n5, \n[1:21:50 remaining, estimate finish 2025-09-24 18:17:41]\n6, \n[1:18:50 remaining, estimate finish 2025-09-24 18:17:01]\n7, \n[1:16:11 remaining, estimate finish 2025-09-24 18:16:41]\n8, \n[1:14:13 remaining, estimate finish 2025-09-24 18:17:12]\n9, \n[1:10:38 remaining, estimate finish 2025-09-24 18:15:42]\n10, \n[1:08:41 remaining, estimate finish 2025-09-24 18:16:14]\n11, \n[1:06:21 remaining, estimate finish 2025-09-24 18:16:16]\n12, \n[1:03:59 remaining, estimate finish 2025-09-24 18:16:17]\n13, \n[1:01:53 remaining, estimate finish 2025-09-24 18:16:40]\n14, \n[59:28 remaining, estimate finish 2025-09-24 18:16:37]\n15, \n[57:03 remaining, estimate finish 2025-09-24 18:16:33]\n16, \n[54:35 remaining, estimate finish 2025-09-24 18:16:25]\n17, \n[52:21 remaining, estimate finish 2025-09-24 18:16:38]\n18, \n[49:57 remaining, estimate finish 2025-09-24 18:16:37]\n19, \n[47:21 remaining, estimate finish 2025-09-24 18:16:12]\n20, \n[44:53 remaining, estimate finish 2025-09-24 18:16:00]\n21, \n[42:23 remaining, estimate finish 2025-09-24 18:15:42]\n22, \n[39:58 remaining, estimate finish 2025-09-24 18:15:35]\n23, \n[37:44 remaining, estimate finish 2025-09-24 18:15:51]\n24, \n[35:23 remaining, estimate finish 2025-09-24 18:15:52]\n25, \n[33:02 remaining, estimate finish 2025-09-24 18:15:53]\n26, \n[30:40 remaining, estimate finish 2025-09-24 18:15:53]\n27, \n[28:11 remaining, estimate finish 2025-09-24 18:15:27]\n28, \n[25:47 remaining, estimate finish 2025-09-24 18:15:17]\n29, \n[23:26 remaining, estimate finish 2025-09-24 18:15:15]\n30, \n[21:06 remaining, estimate finish 2025-09-24 18:15:21]\n31, \n[18:46 remaining, estimate finish 2025-09-24 18:15:24]\n32, \n[16:24 remaining, estimate finish 2025-09-24 18:15:16]\n33, \n[14:04 remaining, estimate finish 2025-09-24 18:15:21]\n34, \n[11:44 remaining, estimate finish 2025-09-24 18:15:24]\n35,  [9:24 remaining] 36,  [7:03 remaining] 37,  [4:42 remaining] 38,  [2:21 remaining] \n39.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n\n### Plot L-function test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(L_9602.csr, . - r ~ r, xlab = \"d\", ylab = \"L(d)-r\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-68-1.png){width=672}\n:::\n:::\n\n\n\n\n## Dental Services - G-function\n\n### G-function estimate\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_86204 = Lest(biz_86204_ppp, correction = \"border\")\nplot(G_86204, xlim = c(0, 500))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-69-1.png){width=672}\n:::\n:::\n\n\n\n\n### Spatial randomness test\n\nThe hypothesis and test are as follows:\n\nHo = The distribution of Beauty services are randomly distributed. H1= The distribution of Beauty services are not randomly distributed. The null hypothesis will be rejected if p-value is smaller than alpha value of 0.01.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_86204.csr <- envelope(biz_86204_ppp, Gest, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n\n### Plot G-function test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(G_86204.csr)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-71-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n### 4.2 Spatio-Temporal analysis\n\n::: panel-tabset\n## Laundry Services\n\n### Perform F-function estimation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9601_quarter_split <- split(biz_9601_quarter_owin, f = as.factor(marks(biz_9601_quarter_owin)))\n\nF_9601_quarter <- lapply(biz_9601_quarter_split, Fest)\n\npar(mfrow = c(3,2), bg = \"#EEEEEE\")\nbiz_9601_quarter_names <- c(\"2024-Q1\", \"2024-Q2\", \"2024-Q3\", \"2024-Q4\", \"2025-Q1\", \"2025-Q2\")\n\nfor (i in 1:6) {\n  plot(F_9601_quarter[[i]],\n       main = paste(\"Laundry Services F-function -\", biz_9601_quarter_names[i]))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-72-1.png){width=1152}\n:::\n:::\n\n\n\n\n### Perform spatial randomness test for each quarter\n\nHypothesis test: H₀ = The distribution of laundry services is randomly distributed. H₁= The distribution of laundry services is not randomly distributed.\n\nAlpha value = 0.01.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_9601_quarter.csr <- lapply(biz_9601_quarter_split, function(x) envelope(x, Fest, nsim = 99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n\n### Plot result of test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(3, 2), bg = \"#EEEEEE\")\nbiz_9601_quarter_labels <- c(paste0(\"2024-Q\", 1:4), paste0(\"2025-Q\", 1:2))\n\nfor (i in 1:6) {\n  plot(F_9601_quarter.csr[[i]], main = paste(\"Laundry F-function:\", biz_9601_quarter_labels[i]))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-74-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Beauty Services\n\n### Perform L-function estimation by month\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_9602_month_split <- split(biz_9602_month_owin, f = as.factor(marks(biz_9602_month_owin)))\n\nL_9602_month <- lapply(biz_9602_month_split, Lest)\n\npar(mfcol = c(9,2), bg = \"#EEEEEE\")\nbiz_9602_month_names <- c(\"2024-1\", \"2024-2\", \"2024-3\", \"2024-4\", \"2024-5\",\"2024-6\",\"2024-7\",\"2024-8\",\"2024-9\",\"2024-10\",\"2024-11\",\"2024-12\", \"2025-1\", \"2025-2\", \"2025-3\", \"2025-4\", \"2025-5\", \"2025-6\")\n\nfor (i in 1:18) {\n  plot(L_9602_month[[i]],\n       main = paste(\"Beauty Services L-function -\", biz_9602_month_names[i]))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-75-1.png){width=1152}\n:::\n:::\n\n\n\n\n### Perform spatial randomness test for each quarter\n\nHypothesis test: H₀ = The distribution of laundry services is randomly distributed. H₁= The distribution of laundry services is not randomly distributed.\n\nAlpha value = 0.01.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_9602_month.csr <- lapply(biz_9602_month_split, function(x) envelope(x, Fest, nsim = 39))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n\n### Plot result of test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(9, 2), bg = \"#EEEEEE\")\nbiz_9602_month_labels <- c(paste0(\"2024-\", 1:12), paste0(\"2025-\", 1:6))\n\nfor (i in 1:18) {\n  plot(L_9602_month.csr[[i]], main = paste(\"Beauty L-function:\", biz_9602_month_labels[i]))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-77-1.png){width=1152}\n:::\n:::\n\n\n\n\n## Dental Services\n\n### Perform G-function estimation by quarter\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_86204_quarter_split <- split(biz_86204_quarter_owin, f = as.factor(marks(biz_86204_quarter_owin)))\n\nG_86204_quarter <- lapply(biz_86204_quarter_split, Gest)\n\npar(mfrow = c(3,2), bg = \"#EEEEEE\")\nbiz_86204_quarter_names <- c(\"2024-Q1\", \"2024-Q2\", \"2024-Q3\", \"2024-Q4\", \"2025-Q1\", \"2025-Q2\", \"2025-Q3\", \"2025-Q4\")\n\nfor (i in 1:6) {\n  plot(G_86204_quarter[[i]], xlim = c(0, 3000),\n       main = paste(\"Dental Services G-function -\", biz_86204_quarter_names[i]))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-78-1.png){width=1152}\n:::\n:::\n\n\n\n\n### Perform spatial randomness test for each quarter\n\nHypothesis test: H₀ = The distribution of laundry services is randomly distributed. H₁= The distribution of laundry services is not randomly distributed.\n\nAlpha value = 0.01.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_86204_quarter.csr <- lapply(biz_86204_quarter_split, function(x) envelope(x, Gest, nsim = 99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n\n### Plot result of test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(3, 2), bg = \"#EEEEEE\")\nbiz_86204_quarter_labels <- c(paste0(\"2024-Q\", 1:4), paste0(\"2025-Q\", 1:2))\n\nfor (i in 1:6) {\n  plot(G_86204_quarter.csr[[i]], xlim = c(0,3000), main = paste(\"Dental G-function:\", biz_86204_quarter_labels[i]))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-80-1.png){width=1152}\n:::\n:::\n\n\n\n:::\n\n## 5 Conclusion\n\ndiscuss how these findings can be used to support urban land use planning and management. (Not more than 500 words)\n\n### 5.1 Key findings\n\n### 5.2 Limitation\n\n### 5.3 Future works\n\n## 6 References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}