{
  "hash": "b29eff1381d31be11806273d38afea73",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"01-Geospatial Data Science with R\"\nauthor: \"Cathy C.\"\ndate: \"Aug 23, 2025\"\ndate-modified: \"last-modified\" #auto render date\nformat: html\nexecute: #how YML page work\n  echo: true #will show code\n  eval: true #will run code every time and show output\n  warning: false #dont show warning msg\n  freeze: true #controls rendering - no render if no changes\n---\n\n\n\n\n## Hands-on 01 Overview\n\n## 1.1 Objectives\n\nIn this exercise, we will learn how to perform geospatial data science tasks in R by using **sf** package.\n\nWe aim to achieve the following competencies:\n\n-   installing and loading [sf](https://r-spatial.github.io/sf/) and [tidyverse](https://www.tidyverse.org/) packages into R environment;\n-   importing geospatial data by using appropriate functions of **sf** package;\n-   importing aspatial data by using appropriate function of **readr** package;\n-   exploring the content of simple feature data frame by using appropriate **Base R** and **sf** functions;\n-   assigning or transforming coordinate systems by using using appropriate *sf* functions;\n-   converting an aspatial data into a sf data frame by using appropriate function of **sf** package;\n-   performing geoprocessing tasks by using appropriate functions of **sf** package;\n-   performing data wrangling tasks by using appropriate functions of **dplyr** package and\n-   performing Exploratory Data Analysis (EDA) by using appropriate functions from **ggplot2** package.\n\n## 1.2 Data Acquisition\n\nWe will extract data sets for this exercise from the following sources:\n\n-   Master Plan 2014 Subzone Boundary (Web) from [data.gov.sg](https://data.gov.sg/)\n-   Pre-Schools [Location](https://data.gov.sg/datasets?query=preschool&resultId=d_61eefab99958fd70e6aab17320a71f1c&page=1) from [data.gov.sg](https://data.gov.sg/)\n-   Cycling Path from [LTADataMall](https://www.mytransport.sg/content/mytransport/home/dataMall.html)\n-   Latest version of Singapore Airbnb listing data from [Inside Airbnb](http://insideairbnb.com/get-the-data.html)\n\n### 1.2.1 Extracting the geospatial data sets\n\nIn the Hands-on_Ex01 folder, we create a sub-folder called data and 2 data sub-folders as geospatial and aspatial respectively. Then, we place `Master Plan 2014 Subzone Boundary (Web)`, `Pre-Schools Location` and `Cycling Path` zipped files into `geospatial` sub-folder and unzipped them. Copy the unzipped files from their respective sub-folders and place them inside geospatial sub-folder.\n\n### 1.2.2 Extracting the aspatial data set\n\nHere we will extract the downloaded `listing` data file. Cut and paste `listing.csv` into `aspatial`sub-folder.\n\n## 1.3 Getting Started\n\nTwo R packages are used in this exercise:\n\n-   **sf** for importing, managing, and processing geospatial data.\n\n-   **tidyverse** for performing data science tasks such as importing, wrangling and visualising data.\n\nThe following packages from the Tidyverse package will be used.\n\n-   **readr** for importing csv data,\n\n-   **tidyr** for manipulating data,\n\n-   **dplyr** for transforming data, and\n\n-   **ggplot2** for visualising data\n\n**pacman** must be installed. We will use the code below to load the necessary R packages into R.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tidyverse)\n```\n:::\n\n\n\n\nWe learn from the code above:\n\np_load function of **pacman** is used to install and load sf and tidyverse packages into R.\n\n## 1.4 Importing Geospatial Data\n\nWe will learn how to import the following geospatial data into R by using [*st_read()*](https://r-spatial.github.io/sf/reference/st_read.html) of **sf** package:\n\n-   `MP14_SUBZONE_WEB_PL`, a polygon feature layer in ESRI shapefile format,\n-   `CyclingPath`, a line feature layer in ESRI shapefile format,\n-   `PreSchool`, a point feature layer in kml file format.\n\n### 1.4.1 Importing polygon feature data in shapefile format\n\nThe code chunk below uses *st_read()* function of **sf** package to import `MP14_SUBZONE_WEB_PL` shapefile into R as a polygon feature data frame.\n\nNote:\n\n-   when the input geospatial data is in shapefile format, two arguments will be used, namely: `dsn` to define the data path and `layer` to provide the shapefile name.\n-   no extension such as .shp, .dbf, .prj and .shx are needed.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/geospatial\",\n               layer = \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `/Users/cathyc/Documents/cathyschu/ISSS626GEO/Hands-on_Ex/Hands-on_Ex01/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n\nLearning:\n\n-   The geospatial objects are multipolygon features.\n-   There are a total of 323 multipolygon features and 15 fields in `mpsz` simple feature data frame. `mpsz` is in **svy21** projected coordinates systems.\n-   The bounding box provides the x extend and y extend of the data.\n\n### 1.4.2 Importing polyline feature data in shapefile form\n\nNow we use *st_read()* function of **sf** package to import `CyclingPath` shapefile into R as line feature data frame.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncyclingpath = st_read(dsn = \"data/geospatial\",\n               layer = \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `/Users/cathyc/Documents/cathyschu/ISSS626GEO/Hands-on_Ex/Hands-on_Ex01/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n\nLearning:\n\n-   There are a total of 4651 features and 19 fields in `cyclingpath` sf data frame.\n-   The geospatial entities are capture in *multilinestring* object.\n-   Similar to the *MP19_SUBZONE_WEB_PL* shape file, this data set is in in **svy21** projected coordinates system too.\n\n### 1.4.3 Importing GIS data in kml format\n\nThe `PreSchoolsLocation` is in [**kml**](https://en.wikipedia.org/wiki/Keyhole_Markup_Language) format. The code chunk below will be used to import the kml into R.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool = st_read(\"data/geospatial/PreSchoolsLocation.kml\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PRESCHOOLS_LOCATION' from data source \n  `/Users/cathyc/Documents/cathyschu/ISSS626GEO/Hands-on_Ex/Hands-on_Ex01/data/geospatial/PreSchoolsLocation.kml' \n  using driver `KML'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n\nLearning from code:\n\n-   `preschool` is a point feature data frame.\n-   There are a total of 2290 features and 2 fields.\n-   Different from the previous two simple feature data frame, preschool is in **wgs84** coordinates system.\n\n## 1.5 Checking the Content of A Simple Feature Data Frame\n\n### 1.5.1 **Working with *st_geometry()***\n\n### 1.5.2\n\n## 1.6\n\n## 1.7\n\n### 1.7.1\n\n### 1.7.2\n\n## 1.8\n\n### 1.8.1\n\n### 1.8.2\n\n## 1.9\n\n### 1.9.1\n\n### 1.9.2\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}